In [1]:

import json
from complexes import response

data=json.loads(response.text)

complexes = data['complexes']

complexe_list=[]
for comp in complexes:
    complexe_list.append({
        "complex_id" : comp["id"],
        "complex_name" : comp["name"]
    })

Venue_list=[]
for comp in complexes:
    for ven in comp.get("venues", []):
        Venue_list.append({
            "id" : ven["id"],
            "name" : ven["name"],
            "city_name" : ven["city_name"],
            "country_name" : ven["country_name"],
            "country_code" : ven["country_code"],
            "timezone" : ven["timezone"],
            "complex_id" : comp["id"]
        })

{"generated_at":"2026-08-05T12:25:31+00:00","complexes":[{"id":"sr:complex:705","name":"Nacional","venues":[{"id":"sr:venue:70045","name":"Cancha Central","city_name":"Santiago","city_id":"sr:city:148","country_name":"Chile","country_code":"CHL","timezone":"America\/Santiago"}]},{"id":"sr:complex:1078","name":"Estadio la Cartuja","venues":[{"id":"sr:venue:74856","name":"Centre Court","city_name":"Seville","city_id":"sr:city:175","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:74858","name":"Court One","city_name":"Seville","city_id":"sr:city:175","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"}]},{"id":"sr:complex:1495","name":"Sibur Arena","venues":[{"id":"sr:venue:1496","name":"Court 1","city_name":"Saint Petersburg","city_id":"sr:city:348","country_name":"Russia","country_code":"RUS","timezone":"Europe\/Moscow"},{"id":"sr:venue:1500","name":"CENTER COURT","city_name":"Saint Petersburg","city_id":"sr:city:348","country_name":"Russia","country_code":"RUS","timezone":"Europe\/Moscow"},{"id":"sr:venue:62149","name":"Sibur Arena","city_name":"Saint Petersburg","city_id":"sr:city:348","country_name":"Russia","country_code":"RUS","timezone":"Europe\/Moscow"},{"id":"sr:venue:62153","name":"TC Dynamo","city_name":"Saint Petersburg","city_id":"sr:city:348","country_name":"Russia","country_code":"RUS","timezone":"Europe\/Moscow"}]},{"id":"sr:complex:2375","name":"Complexo de Tenis do Jamor","venues":[{"id":"sr:venue:57912","name":"Central","city_name":"Oeiras","city_id":"sr:city:7139","country_name":"Portugal","country_code":"PRT","timezone":"Europe\/Lisbon"},{"id":"sr:venue:70805","name":"Campo 3","city_name":"Oeiras","city_id":"sr:city:7139","country_name":"Portugal","country_code":"PRT","timezone":"Europe\/Lisbon"},{"id":"sr:venue:70807","name":"Campo 4","city_name":"Oeiras","city_id":"sr:city:7139","country_name":"Portugal","country_code":"PRT","timezone":"Europe\/Lisbon"},{"id":"sr:venue:77423","name":"Campo 1","city_name":"Oeiras","city_id":"sr:city:7139","country_name":"Portugal","country_code":"PRT","timezone":"Europe\/Lisbon"},{"id":"sr:venue:77437","name":"Campo 8","city_name":"Oeiras","city_id":"sr:city:7139","country_name":"Portugal","country_code":"PRT","timezone":"Europe\/Lisbon"}]},{"id":"sr:complex:4032","name":"Shree Shiv Chhatrapati Sports Complex"},{"id":"sr:complex:5520","name":"O2 Arena"},{"id":"sr:complex:5526","name":"Ostravar Arena","venues":[{"id":"sr:venue:13912","name":"Centre Court","city_name":"Ostrava","city_id":"sr:city:603","country_name":"Czechia","country_code":"CZE","timezone":"Europe\/Prague"},{"id":"sr:venue:13914","name":"Court 3","city_name":"Ostrava","city_id":"sr:city:603","country_name":"Czechia","country_code":"CZE","timezone":"Europe\/Prague"},{"id":"sr:venue:13916","name":"Court 6","city_name":"Ostrava","city_id":"sr:city:603","country_name":"Czechia","country_code":"CZE","timezone":"Europe\/Prague"},{"id":"sr:venue:13942","name":"Court 4","city_name":"Ostrava","city_id":"sr:city:603","country_name":"Czechia","country_code":"CZE","timezone":"Europe\/Prague"},{"id":"sr:venue:55221","name":"Court 1","city_name":"Ostrava","city_id":"sr:city:603","country_name":"Czechia","country_code":"CZE","timezone":"Europe\/Prague"},{"id":"sr:venue:55223","name":"Court 2","city_name":"Ostrava","city_id":"sr:city:603","country_name":"Czechia","country_code":"CZE","timezone":"Europe\/Prague"},{"id":"sr:venue:86772","name":"Ridera Court","city_name":"Ostrava","city_id":"sr:city:603","country_name":"Czechia","country_code":"CZE","timezone":"Europe\/Prague"}]},{"id":"sr:complex:6310","name":"Varazdin Arena","venues":[{"id":"sr:venue:77271","name":"Table 1","city_name":"Varazdin","city_id":"sr:city:1431","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:77273","name":"Table 2","city_name":"Varazdin","city_id":"sr:city:1431","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:77275","name":"Table 3","city_name":"Varazdin","city_id":"sr:city:1431","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:77277","name":"Table 4","city_name":"Varazdin","city_id":"sr:city:1431","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:77279","name":"Table 5","city_name":"Varazdin","city_id":"sr:city:1431","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:77281","name":"Table 6","city_name":"Varazdin","city_id":"sr:city:1431","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:77283","name":"Table 7","city_name":"Varazdin","city_id":"sr:city:1431","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:77285","name":"Table 8","city_name":"Varazdin","city_id":"sr:city:1431","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"}]},{"id":"sr:complex:6322","name":"Castello Dusseldorf","venues":[{"id":"sr:venue:74260","name":"Court 3","city_name":"Dusseldorf","city_id":"sr:city:137","country_name":"Germany","country_code":"DEU","timezone":"Europe\/Berlin"},{"id":"sr:venue:74262","name":"Court 2","city_name":"Dusseldorf","city_id":"sr:city:137","country_name":"Germany","country_code":"DEU","timezone":"Europe\/Berlin"},{"id":"sr:venue:74264","name":"Court 1","city_name":"Dusseldorf","city_id":"sr:city:137","country_name":"Germany","country_code":"DEU","timezone":"Europe\/Berlin"},{"id":"sr:venue:74266","name":"Center Court","city_name":"Dusseldorf","city_id":"sr:city:137","country_name":"Germany","country_code":"DEU","timezone":"Europe\/Berlin"}]},{"id":"sr:complex:6484","name":"Arena Montpellier","venues":[{"id":"sr:venue:2146","name":"Court 1","city_name":"Montpellier","city_id":"sr:city:695","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:19477","name":"Court Patrice Dominguez","city_name":"Montpellier","city_id":"sr:city:695","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:30567","name":"Court Central","city_name":"Montpellier","city_id":"sr:city:695","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:30569","name":"Court 2","city_name":"Montpellier","city_id":"sr:city:695","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:39934","name":"Court 3","city_name":"Montpellier","city_id":"sr:city:695","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"}]},{"id":"sr:complex:6736","name":"Arenes de Metz"},{"id":"sr:complex:6890","name":"Palais des Sports Orleans","venues":[{"id":"sr:venue:66107","name":"Court 2","city_name":"Orleans","city_id":"sr:city:1683","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:66109","name":"Court 3","city_name":"Orleans","city_id":"sr:city:1683","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:66111","name":"Court 4","city_name":"Orleans","city_id":"sr:city:1683","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:70605","name":"Court 5","city_name":"Orleans","city_id":"sr:city:1683","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:74195","name":"Center Court","city_name":"Orleans","city_id":"sr:city:1683","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:74197","name":"Court 1","city_name":"Orleans","city_id":"sr:city:1683","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"}]},{"id":"sr:complex:6904","name":"Stade Pierre-de-Coubertin"},{"id":"sr:complex:7048","name":"Palacio de Deportes Jose Maria Martin Carpena","venues":[{"id":"sr:venue:72565","name":"Pista Cental","city_name":"Malaga","city_id":"sr:city:418","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:72567","name":"Pista 2","city_name":"Malaga","city_id":"sr:city:418","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:72569","name":"Pista 3","city_name":"Malaga","city_id":"sr:city:418","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:72571","name":"Pista 4","city_name":"Malaga","city_id":"sr:city:418","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:83354","name":"Centre Court","city_name":"Malaga","city_id":"sr:city:418","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:83356","name":"Court 2","city_name":"Malaga","city_id":"sr:city:418","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:83358","name":"Court 3","city_name":"Malaga","city_id":"sr:city:418","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"}]},{"id":"sr:complex:7052","name":"Pabellon Municipal Fuente San Luis"},{"id":"sr:complex:7208","name":"Unipol Arena"},{"id":"sr:complex:7242","name":"Telekom Center Athens","venues":[{"id":"sr:venue:85168","name":"Grandstand","city_name":"Athens","city_id":"sr:city:322","country_name":"Greece","country_code":"GRC","timezone":"Europe\/Athens"},{"id":"sr:venue:85170","name":"Center Court","city_name":"Athens","city_id":"sr:city:322","country_name":"Greece","country_code":"GRC","timezone":"Europe\/Athens"}]},{"id":"sr:complex:7778","name":"Arena Gripe"},{"id":"sr:complex:8115","name":"loanDepot park","venues":[{"id":"sr:venue:86200","name":"Center court","city_name":"Miami, FL","city_id":"sr:city:897","country_name":"USA","country_code":"USA","timezone":"America\/New_York"}]},{"id":"sr:complex:9725","name":"Arena Armeets Sofia","venues":[{"id":"sr:venue:17756","name":"Center Court","city_name":"Sofia","city_id":"sr:city:366","country_name":"Bulgaria","country_code":"BGR","timezone":"Europe\/Sofia"},{"id":"sr:venue:17758","name":"Court 1","city_name":"Sofia","city_id":"sr:city:366","country_name":"Bulgaria","country_code":"BGR","timezone":"Europe\/Sofia"},{"id":"sr:venue:23352","name":"Court 3","city_name":"Sofia","city_id":"sr:city:366","country_name":"Bulgaria","country_code":"BGR","timezone":"Europe\/Sofia"},{"id":"sr:venue:23354","name":"Court 4","city_name":"Sofia","city_id":"sr:city:366","country_name":"Bulgaria","country_code":"BGR","timezone":"Europe\/Sofia"},{"id":"sr:venue:23356","name":"Court 2","city_name":"Sofia","city_id":"sr:city:366","country_name":"Bulgaria","country_code":"BGR","timezone":"Europe\/Sofia"}]},{"id":"sr:complex:10063","name":"Kindarena","venues":[{"id":"sr:venue:66889","name":"Center Court","city_name":"Rouen","city_id":"sr:city:1974","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:66925","name":"Amelie Mauresmo","city_name":"Rouen","city_id":"sr:city:1974","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:66979","name":"Celine Dumerc","city_name":"Rouen","city_id":"sr:city:1974","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:74546","name":"Court 1","city_name":"Rouen","city_id":"sr:city:1974","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"}]},{"id":"sr:complex:11769","name":"Estadio German Becker","venues":[{"id":"sr:venue:67857","name":"Cancha Central","city_name":"Temuco","city_id":"sr:city:1724","country_name":"Chile","country_code":"CHL","timezone":"America\/Santiago"},{"id":"sr:venue:67859","name":"Cancha 1","city_name":"Temuco","city_id":"sr:city:1724","country_name":"Chile","country_code":"CHL","timezone":"America\/Santiago"},{"id":"sr:venue:67861","name":"Cancha 2","city_name":"Temuco","city_id":"sr:city:1724","country_name":"Chile","country_code":"CHL","timezone":"America\/Santiago"},{"id":"sr:venue:67863","name":"Cancha 3","city_name":"Temuco","city_id":"sr:city:1724","country_name":"Chile","country_code":"CHL","timezone":"America\/Santiago"}]},{"id":"sr:complex:11981","name":"Netanya Stadium"},{"id":"sr:complex:12241","name":"Palais des sports de Gerland","venues":[{"id":"sr:venue:30465","name":"Indoor 1","city_name":"Lyon","city_id":"sr:city:21","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:30467","name":"Indoor 2","city_name":"Lyon","city_id":"sr:city:21","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:30469","name":"Indoor 3","city_name":"Lyon","city_id":"sr:city:21","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:39773","name":"Court 23","city_name":"Lyon","city_id":"sr:city:21","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:39842","name":"Court 14","city_name":"Lyon","city_id":"sr:city:21","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:39844","name":"Court 15","city_name":"Lyon","city_id":"sr:city:21","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:58692","name":"Court 12","city_name":"Lyon","city_id":"sr:city:21","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"}]},{"id":"sr:complex:15014","name":"Palais Des Sport","venues":[{"id":"sr:venue:15010","name":"La Foret 3","city_name":"Orleans","city_id":"sr:city:1683","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:16880","name":"Central Court","city_name":"Orleans","city_id":"sr:city:1683","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:23652","name":"La Foret 2","city_name":"Orleans","city_id":"sr:city:1683","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:66105","name":"Court 1","city_name":"Orleans","city_id":"sr:city:1683","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:66137","name":"La Foret 4","city_name":"Orleans","city_id":"sr:city:1683","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:66139","name":"La Foret 1","city_name":"Orleans","city_id":"sr:city:1683","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:70603","name":"Court 2","city_name":"Orleans","city_id":"sr:city:1683","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"}]},{"id":"sr:complex:15371","name":"Palasport","venues":[{"id":"sr:venue:67869","name":"Court 2","city_name":"Andria","city_id":"sr:city:1665","country_name":"Italy","country_code":"ITA","timezone":"Europe\/Rome"},{"id":"sr:venue:67871","name":"Court 3","city_name":"Andria","city_id":"sr:city:1665","country_name":"Italy","country_code":"ITA","timezone":"Europe\/Rome"},{"id":"sr:venue:68095","name":"Campo Tato Paride","city_name":"Andria","city_id":"sr:city:1665","country_name":"Italy","country_code":"ITA","timezone":"Europe\/Rome"},{"id":"sr:venue:68097","name":"Campo Arpex","city_name":"Andria","city_id":"sr:city:1665","country_name":"Italy","country_code":"ITA","timezone":"Europe\/Rome"}]},{"id":"sr:complex:16020","name":"Salle Steredenn","venues":[{"id":"sr:venue:16022","name":"Atg 3","city_name":"Saint-Brieuc","city_id":"sr:city:1261","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:18015","name":"Atg 4","city_name":"Saint-Brieuc","city_id":"sr:city:1261","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:28371","name":"Tcsb 4","city_name":"Saint-Brieuc","city_id":"sr:city:1261","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:28373","name":"Tcsb 3","city_name":"Saint-Brieuc","city_id":"sr:city:1261","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:62697","name":"Court Steredenn","city_name":"Saint-Brieuc","city_id":"sr:city:1261","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:80523","name":"Court TCSB","city_name":"Saint-Brieuc","city_id":"sr:city:1261","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:86972","name":"Court Mairie de Saint-Brieuc","city_name":"Saint-Brieuc","city_id":"sr:city:1261","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"}]},{"id":"sr:complex:16069","name":"Garanti Koza Arena","venues":[{"id":"sr:venue:14874","name":"Court Limak Enerji","city_name":"Istanbul","city_id":"sr:city:326","country_name":"Turkiye","country_code":"TUR","timezone":"Europe\/Istanbul"}]},{"id":"sr:complex:16612","name":"Porsche-Arena","venues":[{"id":"sr:venue:1765","name":"Centre Court","city_name":"Stuttgart","city_id":"sr:city:103","country_name":"Germany","country_code":"DEU","timezone":"Europe\/Berlin"},{"id":"sr:venue:77411","name":"Court 1","city_name":"Stuttgart","city_id":"sr:city:103","country_name":"Germany","country_code":"DEU","timezone":"Europe\/Berlin"},{"id":"sr:venue:77413","name":"Court 2","city_name":"Stuttgart","city_id":"sr:city:103","country_name":"Germany","country_code":"DEU","timezone":"Europe\/Berlin"}]},{"id":"sr:complex:17254","name":"Poliesportiu d'Andorra"},{"id":"sr:complex:17869","name":"Rizal Memorial Stadium","venues":[{"id":"sr:venue:17694","name":"Court 1","city_name":"Manila","city_id":"sr:city:8618","country_name":"Philippines","country_code":"PHL","timezone":"Asia\/Manila"},{"id":"sr:venue:86692","name":"CENTER","city_name":"Manila","city_id":"sr:city:8618","country_name":"Philippines","country_code":"PHL","timezone":"Asia\/Manila"},{"id":"sr:venue:86696","name":"Court 2","city_name":"Manila","city_id":"sr:city:8618","country_name":"Philippines","country_code":"PHL","timezone":"Asia\/Manila"}]},{"id":"sr:complex:17945","name":"Rotterdam Ahoy","venues":[{"id":"sr:venue:1648","name":"Court 1","city_name":"Rotterdam","city_id":"sr:city:79","country_name":"Netherlands","country_code":"NLD","timezone":"Europe\/Brussels"},{"id":"sr:venue:3696","name":"Court 2","city_name":"Rotterdam","city_id":"sr:city:79","country_name":"Netherlands","country_code":"NLD","timezone":"Europe\/Brussels"},{"id":"sr:venue:15644","name":"Court 3","city_name":"Rotterdam","city_id":"sr:city:79","country_name":"Netherlands","country_code":"NLD","timezone":"Europe\/Brussels"},{"id":"sr:venue:22854","name":"Centre Court","city_name":"Rotterdam","city_id":"sr:city:79","country_name":"Netherlands","country_code":"NLD","timezone":"Europe\/Brussels"}]},{"id":"sr:complex:18201","name":"The O2","venues":[{"id":"sr:venue:66121","name":"Centre Court","city_name":"London","city_id":"sr:city:27","country_name":"England","country_code":"ENG","timezone":"Europe\/London"}]},{"id":"sr:complex:18221","name":"Bluesun Tennis Center","venues":[{"id":"sr:venue:18223","name":"Cedevita Court","city_name":"Bol","city_id":"sr:city:1276","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:18225","name":"Cockta Court","city_name":"Bol","city_id":"sr:city:1276","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:18227","name":"Kala Court","city_name":"Bol","city_id":"sr:city:1276","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:21412","name":"INA Court","city_name":"Bol","city_id":"sr:city:1276","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:21422","name":"Raiffeisen Court","city_name":"Bol","city_id":"sr:city:1276","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:30195","name":"Lukas Court","city_name":"Bol","city_id":"sr:city:1276","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:39715","name":"Center Court","city_name":"Bol","city_id":"sr:city:1276","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:39717","name":"Court 1","city_

In [2]:
import pandas as pd
complexes_df = pd.DataFrame(complexe_list)
complexes_df

           complex_id                           complex_name
0      sr:complex:705                               Nacional
1     sr:complex:1078                     Estadio la Cartuja
2     sr:complex:1495                            Sibur Arena
3     sr:complex:2375             Complexo de Tenis do Jamor
4     sr:complex:4032  Shree Shiv Chhatrapati Sports Complex
..                ...                                    ...
764  sr:complex:88070                             Ntc Kosice
765  sr:complex:88548                         MAX TENIS CLUB
766  sr:complex:88662                      Cranbrook Schools
767  sr:complex:88816                Yarbrough Tennis Center
768  sr:complex:88916               Queensland Tennis Centre

[769 rows x 2 columns]

In [3]:
venues_df = pd.DataFrame(Venue_list)
venues_df

,id,name,city_name,country_name,country_code,timezone,complex_id
0,sr:venue:70045,Cancha Central,Santiago,Chile,CHL,America/Santiago,sr:complex:705
1,sr:venue:74856,Centre Court,Seville,Spain,ESP,Europe/Madrid,sr:complex:1078
2,sr:venue:74858,Court One,Seville,Spain,ESP,Europe/Madrid,sr:complex:1078
3,sr:venue:1496,Court 1,Saint Petersburg,Russia,RUS,Europe/Moscow,sr:complex:1495
4,sr:venue:1500,CENTER COURT,Saint Petersburg,Russia,RUS,Europe/Moscow,sr:complex:1495
...,...,...,...,...,...,...,...
4049,sr:venue:88906,Queensland Tennis Centre - Court 08,Brisbane,Australia,AUS,Australia/Brisbane,sr:complex:88916
4050,sr:venue:88908,Queensland Tennis Centre - Court 01,Brisbane,Australia,AUS,Australia/Brisbane,sr:complex:88916
4051,sr:venue:88910,Queensland Tennis Centre - Court 06,Brisbane,Australia,AUS,Australia/Brisbane,sr:complex:88916
4052,sr:venue:88912,Queensland Tennis Centre - Court 02,Brisbane,Australia,AUS,Australia/Brisbane,sr:complex:88916
4053,sr:venue:88914,Queensland Tennis Centre - Court 04,Brisbane,Australia,AUS,Australia/Brisbane,sr:complex:88916

In [4]:
complexes_d= complexes_df.drop_duplicates()
print(complexes_d)

           complex_id                           complex_name
0      sr:complex:705                               Nacional
1     sr:complex:1078                     Estadio la Cartuja
2     sr:complex:1495                            Sibur Arena
3     sr:complex:2375             Complexo de Tenis do Jamor
4     sr:complex:4032  Shree Shiv Chhatrapati Sports Complex
..                ...                                    ...
764  sr:complex:88070                             Ntc Kosice
765  sr:complex:88548                         MAX TENIS CLUB
766  sr:complex:88662                      Cranbrook Schools
767  sr:complex:88816                Yarbrough Tennis Center
768  sr:complex:88916               Queensland Tennis Centre

[769 rows x 2 columns]

In [5]:
complexes_d.to_csv("complexes.csv")

In [6]:
venues_d= venues_df.drop_duplicates()
print(venues_d)

                  id                                 name         city_name  \
0     sr:venue:70045                       Cancha Central          Santiago
1     sr:venue:74856                         Centre Court           Seville
2     sr:venue:74858                            Court One           Seville
3      sr:venue:1496                              Court 1  Saint Petersburg
4      sr:venue:1500                         CENTER COURT  Saint Petersburg
...              ...                                  ...               ...
4049  sr:venue:88906  Queensland Tennis Centre - Court 08          Brisbane
4050  sr:venue:88908  Queensland Tennis Centre - Court 01          Brisbane
4051  sr:venue:88910  Queensland Tennis Centre - Court 06          Brisbane
4052  sr:venue:88912  Queensland Tennis Centre - Court 02          Brisbane
4053  sr:venue:88914  Queensland Tennis Centre - Court 04          Brisbane

     country_name country_code            timezone        complex_id
0           Chile          CHL    America/Santiago    sr:complex:705
1           Spain          ESP       Europe/Madrid   sr:complex:1078
2           Spain          ESP       Europe/Madrid   sr:complex:1078
3          Russia          RUS       Europe/Moscow   sr:complex:1495
4          Russia          RUS       Europe/Moscow   sr:complex:1495
...           ...          ...                 ...               ...
4049    Australia          AUS  Australia/Brisbane  sr:complex:88916
4050    Australia          AUS  Australia/Brisbane  sr:complex:88916
4051    Australia          AUS  Australia/Brisbane  sr:complex:88916
4052    Australia          AUS  Australia/Brisbane  sr:complex:88916
4053    Australia          AUS  Australia/Brisbane  sr:complex:88916

[4054 rows x 7 columns]

In [7]:
venues_d.to_csv("venues.csv")

In [8]:

import mysql.connector

mydb = mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password="12@Musk@n4595",
    database="tennis_db"
)

cursor = mydb.cursor(buffered=True)

In [9]:
from tabulate import tabulate
complex_query = "INSERT INTO complexes(complex_id,complex_name) VALUES (%s, %s)"

complex_data = complexes_d[['complex_id','complex_name']].values.tolist()

cursor.executemany(complex_query, complex_data)
mydb.commit()

In [10]:
cursor.execute("SELECT COUNT(*) FROM complexes")
out=cursor.fetchall()
print(tabulate(out, headers=[i[0] for i in cursor.description],  tablefmt='psql'))

+------------+
|   COUNT(*) |
|------------|
|        769 |
+------------+

In [11]:
cursor.execute("SELECT * FROM complexes")
out=cursor.fetchall()
print(tabulate(out, headers=[i[0] for i in cursor.description],  tablefmt='psql'))

+------------------+------------------------------------------------------------+
| complex_id       | complex_name                                               |
|------------------+------------------------------------------------------------|
| sr:complex:10063 | Kindarena                                                  |
| sr:complex:1078  | Estadio la Cartuja                                         |
| sr:complex:11769 | Estadio German Becker                                      |
| sr:complex:11981 | Netanya Stadium                                            |
| sr:complex:12241 | Palais des sports de Gerland                               |
| sr:complex:1495  | Sibur Arena                                                |
| sr:complex:15014 | Palais Des Sport                                           |
| sr:complex:15371 | Palasport                                                  |
| sr:complex:16020 | Salle Steredenn                                            |
| sr:complex:16069 | Garanti Koza Arena                                         |
| sr:complex:16612 | Porsche-Arena                                              |
| sr:complex:17254 | Poliesportiu d'Andorra                                     |
| sr:complex:17869 | Rizal Memorial Stadium                                     |
| sr:complex:17945 | Rotterdam Ahoy                                             |
| sr:complex:18201 | The O2                                                     |
| sr:complex:18221 | Bluesun Tennis Center                                      |
| sr:complex:19166 | Shlomo Group Arena                                         |
| sr:complex:19737 | Club Sonoma, Estadio Gnp Seguros                           |
| sr:complex:19951 | Accor Arena                                                |
| sr:complex:21870 | Stadium Goran Ivanisevic in ITC Stella Maris               |
| sr:complex:21910 | Roy Emerson Arena                                          |
| sr:complex:23576 | Brest Arena                                                |
| sr:complex:2375  | Complexo de Tenis do Jamor                                 |
| sr:complex:26983 | Club de Tenis Puente Romano                                |
| sr:complex:26985 | National Tennis Center                                     |
| sr:complex:27093 | Canberra Tennis Centre                                     |
| sr:complex:27095 | BT Arena                                                   |
| sr:complex:27697 | Ford Center at The Star                                    |
| sr:complex:28457 | Valletta Cambiaso ASD                                      |
| sr:complex:28617 | Porsche Arena                                              |
| sr:complex:28926 | Royal Arena                                                |
| sr:complex:32327 | Taipei Arena                                               |
| sr:complex:32403 | Ohio State University GC                                   |
| sr:complex:32668 | Shenzhen Bay Sports Center                                 |
| sr:complex:32812 | Singapore Indoor Stadium                                   |
| sr:complex:33156 | IMG Academy                                                |
| sr:complex:33186 | Palais des Sports de Marseille                             |
| sr:complex:33188 | Caja Magica                                                |
| sr:complex:33190 | All England Lawn Tennis and Croquet Club                   |
| sr:complex:33192 | Stade Roland Garros                                        |
| sr:complex:33194 | Complexe Al Amal                                           |
| sr:complex:33196 | Melbourne Park                                             |
| sr:complex:33198 | Qi zhong Forest Sports City Arena                          |
| sr:complex:33200 | Wake Forest University Tennis Complex                      |
| sr:complex:33204 | Clube de Ténis do Estoril                                  |
| sr:complex:33206 | The Drive                                                  |
| sr:complex:33208 | Atlantic Station                                           |
| sr:complex:33210 | International Tennis Hall of Fame                          |
| sr:complex:33214 | Club Jacaranda Cumbaya                                     |
| sr:complex:33218 | Hengqin International Tennis Center Zhuhai                 |
| sr:complex:33222 | Buenos Aires Lawn Tennis Club                              |
| sr:complex:33226 | The Racquet Club of Memphis                                |
| sr:complex:33228 | Delray Beach Tennis Center                                 |
| sr:complex:33230 | CK Sportcenter Kockelscheuer                               |
| sr:complex:33232 | Singapore Sports Hub                                       |
| sr:complex:33234 | Linzer Sporthalle                                          |
| sr:complex:33236 | Luzhniki Olympic Complex                                   |
| sr:complex:33238 | Ariake Coliseum & Ariake Tennis Forest Park                |
| sr:complex:33240 | Optics Valley International Tennis Center                  |
| sr:complex:33242 | Guangzhou Tianhe Sports Center                             |
| sr:complex:33244 | Olympic Park Tennis Center                                 |
| sr:complex:33246 | Victoria Park Tennis Court                                 |
| sr:complex:33248 | Tianjin Tuanbo International Tennis Center                 |
| sr:complex:33250 | Tashkent Tennis Centreake                                  |
| sr:complex:33252 | China National Tennis Center                               |
| sr:complex:33254 | Utsubo Tennis Center                                       |
| sr:complex:33258 | Connecticut Tennis Center                                  |
| sr:complex:33262 | Santa Catarina Tennis Federation                           |
| sr:complex:33264 | Baku Tennis Academy                                        |
| sr:complex:33266 | Sobeys Stadium                                             |
| sr:complex:33268 | Lindner Family Tennis Center                               |
| sr:complex:33270 | Taube Tennis Stadium                                       |
| sr:complex:33274 | Tennis Club de Strasbourg                                  |
| sr:complex:33276 | Edgbaston Priory Club                                      |
| sr:complex:33278 | Royal Tennis Club de Marrakech                             |
| sr:complex:33280 | Tennis Club 1.FCN                                          |
| sr:complex:33282 | Devonshire Park Lawn Tennis Centre                         |
| sr:complex:33286 | Tennis Club Sparta Praha                                   |
| sr:complex:33288 | Club Campestre El Rancho                                   |
| sr:complex:33290 | Khalifa International Tennis & Squash Complex              |
| sr:complex:33292 | Club Sonoma                                                |
| sr:complex:33294 | Centre Municipal de Tennis Vall d Hebron                   |
| sr:complex:33296 | Jockey Club Brasileiro                                     |
| sr:complex:33298 | Acapulco Princess Mundo Imperial                           |
| sr:complex:33300 | Tennis Center at Crandon Park                              |
| sr:complex:33302 | Family Circle Tennis Center                                |
| sr:complex:33306 | Indian Wells Tennis Garden                                 |
| sr:complex:33310 | Aviation Club Tennis Centre                                |
| sr:complex:33316 | Indianapolis Tennis Center                                 |
| sr:complex:33318 | SKT Sopot                                                  |
| sr:complex:33320 | St Jakobshalle Basel                                       |
| sr:complex:33322 | Wiener Stadthalle                                          |
| sr:complex:33324 | L'Agora                                                    |
| sr:complex:33328 | ASB Tennis Centre                                          |
| sr:complex:33332 | NSW Tennis Centre                                          |
| sr:complex:33334 | Shenzhen Longgang Sports Center                            |
| sr:complex:33338 | Am Rothenbaum                                              |
| sr:complex:33340 | Kungliga Tennishallen                                      |
| sr:complex:33342 | Kitzbuhel Tennis Club Sportfeld 2                          |
| sr:complex:33344 | The Queen's Club                                           |
| sr:complex:33346 | Gerry Weber Stadium                                        |
| sr:complex:33348 | Nottingham Tennis Centre                                   |
| sr:complex:33350 | Bastad Tennis Stadium                                      |
| sr:complex:33354 | Nice Lawn Tennis Club                                      |
| sr:complex:33356 | Tennis Club de Geneve                                      |
| sr:complex:33358 | Koza World of Sport Complex                                |
| sr:complex:33364 | Autotron Rosmalen                                          |
| sr:complex:33366 | BNR arena                                                  |
| sr:complex:33368 | MTTC Iphitos e.V.                                          |
| sr:complex:33372 | Real Club de Tenis Barcelona                               |
| sr:complex:33374 | Hiroshima Regional Park                                    |
| sr:complex:33380 | Europe Tennis Center                                       |
| sr:complex:33382 | Tennis Club Lido Lugano                                    |
| sr:complex:33386 | Nemzeti Edzes Kozpont                                      |
| sr:complex:33388 | Union Sportive des Cheminots du Maroc                      |
| sr:complex:33390 | Tennis Club de Lyon                                        |
| sr:complex:33392 | Sichuan International Tennis Center                        |
| sr:complex:33394 | Swiss Tennis Arena                                         |
| sr:complex:33400 | Nanchang International Tennis Center                       |
| sr:complex:33402 | Louisville Boat Club                                       |
| sr:complex:33406 | Rochusclub                                                 |
| sr:complex:33408 | Shenzhen Luohu Tennis Centre                               |
| sr:complex:33410 | Yang-Ming Tennis Centre                                    |
| sr:complex:33418 | Mallorca Country Club Santa Ponsa                          |
| sr:complex:33422 | Royal Primerose Tennis Club                                |
| sr:complex:33424 | The Tennis Center at College Park                          |
| sr:complex:33426 | Tennis Center Novak                                        |
| sr:complex:33428 | Farum Arena                                                |
| sr:complex:33430 | Racquet Club of the South                                  |
| sr:complex:33434 | Atlanta Athletic Club                                      |
| sr:complex:33436 | Madrid Arena                                               |
| sr:complex:33438 | Club Avantage Multi-Sports                                 |
| sr:complex:33440 | Rama Gardens Hotel                                         |
| sr:complex:33442 | Delmar International School                                |
| sr:complex:33444 | OMNI LA COSTA RESORT & SPA                                 |
| sr:complex:33446 | Country Time Club                                          |
| sr:complex:33448 | ŠRC MARINA PORTOROŽ                                        |
| sr:complex:33450 | Fangcun Tennis Sports Center                               |
| sr:complex:33454 | Netaji Indoor Stadium                                      |
| sr:complex:33456 | Holiday Inn Crowne Plaza Hotel Asheville                   |
| sr:complex:33458 | Ligue d'Alsace de Tennis                                   |
| sr:complex:33460 | I. Czech Lawn Tennis Club Praha                            |
| sr:complex:33462 | Fes Country Club                                           |
| sr:complex:33464 | KSLTA Signature - Kingfisher Stadium                       |
| sr:complex:33466 | Warszawianka Tennis Centre                                 |
| sr:complex:33468 | LTTC Rot-Weiss                                             |
| sr:complex:33470 | Amelia Island Plantation Resort                            |
| sr:complex:33472 | Romai Tennis Academy                                       |
| sr:complex:33474 | El Recinto Ferial Casa de Campo                            |
| sr:complex:33476 | Impact Arena                                               |
| sr:complex:33478 | Tokyo Metropolitan Gymnasium                               |
| sr:complex:33480 | Darling Tennis Center                                      |
| sr:complex:33482 | Sporting Club de Tenis Valencia                            |
| sr:complex:33484 | Pörtschach Werzer Arena                                    |
| sr:complex:33486 | Club Naval de Campo las Salinas                            |
| sr:complex:33488 | Hilton DFW Lakes                                           |
| sr:complex:33490 | Sportingclub Bokkeduinen                                   |
| sr:complex:33492 | Baku Tennis Academy                                        |
| sr:complex:33530 | Paris La Defense Arena                                     |
| sr:complex:33618 | Copper Box Arena                                           |
| sr:complex:33808 | USTA Billie Jean King National Tennis Center               |
| sr:complex:34336 | Emirates Arena                                             |
| sr:complex:34586 | Lanxess Arena                                              |
| sr:complex:34736 | Tiburon Peninsula Club                                     |
| sr:complex:34766 | Country Club de Bogota                                     |
| sr:complex:34812 | Almaty Tennis Center                                       |
| sr:complex:34814 | Sociedade Hipica de Campinas                               |
| sr:complex:34816 | Eve Zimmermann Tennis Center                               |
| sr:complex:34896 | Circolo del Tennis Firenze 1898                            |
| sr:complex:35048 | Sanchez-Casal Tennis Academy                               |
| sr:complex:35052 | Santo Domingo Tennis Club La Bocha                         |
| sr:complex:35054 | Solano Community College Tennis Center                     |
| sr:complex:35142 | Lotto Arena                                                |
| sr:complex:35212 | TC Ismaning                                                |
| sr:complex:35214 | Osten & Victor Alberta Tennis Centre                       |
| sr:complex:35236 | Ningbo Tennis Center of WTA Ningbo, China w42              |
| sr:complex:35290 | Club Tennis Las Terrazas de Miraflores                     |
| sr:complex:35292 | Liuzhou Tennis Center                                      |
| sr:complex:35458 | Shree Shiv Chhatrapati Sports Complex                      |
| sr:complex:35512 | Boars Head Resort                                          |
| sr:complex:35516 | Anexo Guayaquil Tennis Club                                |
| sr:complex:35580 | Uber Arena                                                 |
| sr:complex:35592 | Sporting Milano 3                                          |
| sr:complex:35638 | Fiera Milano stadium                                       |
| sr:complex:35640 | AXA Arena NTC                                              |
| sr:complex:35642 | Vendéspace                                                 |
| sr:complex:35644 | Carrasco Lawn Tennis Club                                  |
| sr:complex:35646 | Goodfriend Indoor Tennis Center                            |
| sr:complex:35648 | Palais des sports de Beaublanc                             |
| sr:complex:35684 | Miki Disaster Management Park                              |
| sr:complex:35688 | Karnataka State Lawn Tennis Association                    |
| sr:complex:35690 | Racket Club, Argentina                                     |
| sr:complex:35692 | Atkins Tennis Center                                       |
| sr:complex:35694 | Rice Stadium (Brian Patterson Sports Performance Center)   |
| sr:complex:35870 | Mhalunge Balewadi Tennis Complex                           |
| sr:complex:35902 | Palazzetto dello Sport                                     |
| sr:complex:36493 | Manuka Doctor Arena                                        |
| sr:complex:36495 | Domain Tennis Centre                                       |
| sr:complex:36497 | Ohio State Varsity Tennis Center                           |
| sr:complex:36573 | EPG Arena                                                  |
| sr:complex:36783 | Newport Beach Tennis Club                                  |
| sr:complex:36785 | Burnie Tennis Club                                         |
| sr:complex:36787 | Cantegril Country Club                                     |
| sr:complex:37001 | Francoise Savatier                                         |
| sr:complex:37003 | Francoise Savatier                                         |
| sr:complex:37007 | Salle Collete-Benson                                       |
| sr:complex:38029 | True Arena Hua Hin                                         |
| sr:complex:38041 | Launceston Regional Tennis Centre                          |
| sr:complex:38043 | True Arena Hua Hin                                         |
| sr:complex:38045 | Parc des Expositions Quimper Cornouaille                   |
| sr:complex:38047 | Cleveland Racquet Club                                     |
| sr:complex:38187 | Sud de France Arena                                        |
| sr:complex:38189 | Estadio Mario Alberto Kempes                               |
| sr:complex:38191 | T Bar M Racquet Club                                       |
| sr:complex:38193 | SYMA Sports and Conference Centre                          |
| sr:complex:38195 | SDAT Tennis Stadium                                        |
| sr:complex:38277 | Club Campestre Sede Llanogrande                            |
| sr:complex:38285 | Complexe Sportif Chantereyne                               |
| sr:complex:38313 | Dubai Duty Free Tennis Stadium                             |
| sr:complex:38315 | Hotel Racquet Cuernavaca                                   |
| sr:complex:38419 | Indian Wells Tennis Garden                                 |
| sr:complex:38421 | Mamushidani Tennis Courts, Keio University                 |
| sr:complex:38451 | Palais des Sports de Pau                                   |
| sr:complex:38483 | Manquehue Sports Club                                      |
| sr:complex:38603 | Shenzhen International Tennis Center                       |
| sr:complex:38625 | The Phoenix Country Club                                   |
| sr:complex:38631 | The Phoenix Country Club                                   |
| sr:complex:38678 | Hard Rock Stadium                                          |
| sr:complex:38680 | Centro Panamericano de Tenis                               |
| sr:complex:38684 | Club Los Lagartos                                          |
| sr:complex:38690 | TK Sparta Praha                                            |
| sr:complex:38692 | Hot Springs Tennis Center                                  |
| sr:complex:38698 | La Caja Magica                                             |
| sr:complex:38702 | Tennis Club Kastela                                        |
| sr:complex:38704 | River Oaks Country Club                                    |
| sr:complex:38712 | National Tennis Center                                     |
| sr:complex:38716 | Clube de Tenis do Estoril                                  |
| sr:complex:38720 | Parc De La TeTe D'or                                       |
| sr:complex:38722 | Tennis Club Weissenhof                                     |
| sr:complex:38732 | Tennis Club Lillois Lille Metropole                        |

In [12]:
venues_d.columns

Index(['id', 'name', 'city_name', 'country_name', 'country_code', 'timezone',
       'complex_id'],
      dtype='str')

In [13]:
venue_query = "INSERT INTO venues(venue_id,venue_name,city_name,country_name,country_code,timezone,complex_id) VALUES (%s, %s, %s, %s, %s, %s, %s)"

venue_data = venues_d[['id','name','city_name','country_name','country_code','timezone','complex_id']].values.tolist()

cursor.executemany(venue_query, venue_data)
mydb.commit()

In [15]:
cursor.execute("SELECT COUNT(*) FROM venues")
out=cursor.fetchall()
print(tabulate(out, headers=[i[0] for i in cursor.description],  tablefmt='psql'))

+------------+
|   COUNT(*) |
|------------|
|       4054 |
+------------+

In [16]:
cursor.execute("SELECT * FROM venues")
out=cursor.fetchall()
print(tabulate(out, headers=[i[0] for i in cursor.description],  tablefmt='psql'))

+----------------+--------------------------------------------------------------+----------------------------+----------------------+----------------+--------------------------------+------------------+
| venue_id       | venue_name                                                   | city_name                  | country_name         | country_code   | timezone                       | complex_id       |
|----------------+--------------------------------------------------------------+----------------------------+----------------------+----------------+--------------------------------+------------------|
| sr:venue:1008  | Estadio Monumental                                           | Lima                       | Peru                 | PER            | America/Lima                   | sr:complex:35290 |
| sr:venue:10390 | Stadium                                                      | Shenzhen                   | China                | CHN            | Asia/Shanghai                  | sr:complex:38603 |
| sr:venue:10394 | Court 2                                                      | Shenzhen                   | China                | CHN            | Asia/Shanghai                  | sr:complex:33334 |
| sr:venue:10472 | Court 7                                                      | Sydney                     | Australia            | AUS            | Australia/Sydney               | sr:complex:33244 |
| sr:venue:10536 | Court 20                                                     | Melbourne                  | Australia            | AUS            | Australia/Melbourne            | sr:complex:33196 |
| sr:venue:10538 | Court 22                                                     | Melbourne                  | Australia            | AUS            | Australia/Melbourne            | sr:complex:33196 |
| sr:venue:10582 | Estadio Ivan Elias Moreno                                    | Lima                       | Peru                 | PER            | America/Lima                   | sr:complex:35290 |
| sr:venue:10644 | Stade Numa-Daly Magenta                                      | Noumea                     | New Caledonia        | NCL            | Pacific/Noumea                 | sr:complex:49635 |
| sr:venue:11388 | Cancha 5                                                     | Acapulco                   | Mexico               | MEX            | America/Mexico_City            | sr:complex:33298 |
| sr:venue:11486 | Court 13                                                     | Indian Wells               | USA                  | USA            | America/Los_Angeles            | sr:complex:38419 |
| sr:venue:11661 | Center Court                                                 | Marrakech                  | Morocco              | MAR            | Africa/Casablanca              | sr:complex:33278 |
| sr:venue:11663 | Court 1                                                      | Marrakech                  | Morocco              | MAR            | Africa/Casablanca              | sr:complex:33278 |
| sr:venue:11665 | Court 2                                                      | Marrakech                  | Morocco              | MAR            | Africa/Casablanca              | sr:complex:33278 |
| sr:venue:11667 | Court 4                                                      | Marrakech                  | Morocco              | MAR            | Africa/Casablanca              | sr:complex:33278 |
| sr:venue:11735 | SZ Court                                                     | Munich                     | Germany              | DEU            | Europe/Berlin                  | sr:complex:33368 |
| sr:venue:11741 | Campo 1                                                      | Oeiras                     | Portugal             | PRT            | Europe/Lisbon                  | sr:complex:77763 |
| sr:venue:11985 | Center Court                                                 | Nuremberg                  | Germany              | DEU            | Europe/Berlin                  | sr:complex:33280 |
| sr:venue:11987 | Show Court                                                   | Nuremberg                  | Germany              | DEU            | Europe/Berlin                  | sr:complex:33280 |
| sr:venue:11989 | Court 1                                                      | Nuremberg                  | Germany              | DEU            | Europe/Berlin                  | sr:complex:33280 |
| sr:venue:11995 | Court 2                                                      | Nuremberg                  | Germany              | DEU            | Europe/Berlin                  | sr:complex:33280 |
| sr:venue:12005 | Court 9                                                      | Palermo                    | Italy                | ITA            | Europe/Rome                    | sr:complex:33446 |
| sr:venue:12045 | Court 11                                                     | Palermo                    | Italy                | ITA            | Europe/Rome                    | sr:complex:33446 |
| sr:venue:12245 | Halle des Sports                                             | Quimper                    | France               | FRA            | Europe/Paris                   | sr:complex:38045 |
| sr:venue:1308  | Court 4                                                      | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:1310  | Arthur Ashe Stadium                                          | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:1311  | Court 5                                                      | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:1312  | Court 6                                                      | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:1313  | Court 7                                                      | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:1314  | Court 8                                                      | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:1315  | Court 9                                                      | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:1316  | Court 10                                                     | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:1317  | Court 11                                                     | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:1318  | Court 12                                                     | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:1319  | Court 13                                                     | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:13196 | Court A                                                      | Shanghai                   | China                | CHN            | Asia/Shanghai                  | sr:complex:44518 |
| sr:venue:13198 | Court B                                                      | Shanghai                   | China                | CHN            | Asia/Shanghai                  | sr:complex:44518 |
| sr:venue:1320  | Court 14                                                     | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:13200 | Court C                                                      | Shanghai                   | China                | CHN            | Asia/Shanghai                  | sr:complex:44518 |
| sr:venue:1321  | Court 15                                                     | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:13212 | Cancha 10                                                    | Buenos Aires               | Argentina            | ARG            | America/Argentina/Buenos_Aires | sr:complex:33222 |
| sr:venue:13214 | Cancha 11                                                    | Buenos Aires               | Argentina            | ARG            | America/Argentina/Buenos_Aires | sr:complex:33222 |
| sr:venue:13216 | Cancha 2                                                     | Buenos Aires               | Argentina            | ARG            | America/Argentina/Buenos_Aires | sr:complex:33222 |
| sr:venue:1322  | Court 16                                                     | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:1323  | Stadium 17                                                   | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:1324  | Louis Armstrong Stadium                                      | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:1325  | Grandstand                                                   | New York, NY               | USA                  | USA            | America/New_York               | sr:complex:33808 |
| sr:venue:13308 | Center Court                                                 | Shenzhen                   | China                | CHN            | Asia/Shanghai                  | sr:complex:33334 |
| sr:venue:13366 | Court 2                                                      | Montpellier                | France               | FRA            | Europe/Paris                   | sr:complex:38187 |
| sr:venue:1339  | Court Central                                                | Metz                       | France               | FRA            | Europe/Paris                   | sr:complex:44130 |
| sr:venue:1340  | Court 1                                                      | Metz                       | France               | FRA            | Europe/Paris                   | sr:complex:44130 |
| sr:venue:1341  | CENTRALA                                                     | Bucharest                  | Romania              | ROU            | Europe/Bucharest               | sr:complex:33366 |
| sr:venue:1342  | SEMI CENTRALA                                                | Bucharest                  | Romania              | ROU            | Europe/Bucharest               | sr:complex:33366 |
| sr:venue:1343  | Court 2                                                      | Bucharest                  | Romania              | ROU            | Europe/Bucharest               | sr:complex:60416 |
| sr:venue:1344  | CENTRE                                                       | Tashkent                   | Uzbekistan           | UZB            | Asia/Tashkent                  | sr:complex:44522 |
| sr:venue:1345  | COURT 3                                                      | Tashkent                   | Uzbekistan           | UZB            | Asia/Tashkent                  | sr:complex:44522 |
| sr:venue:1346  | COURT 4                                                      | Tashkent                   | Uzbekistan           | UZB            | Asia/Tashkent                  | sr:complex:44522 |
| sr:venue:1347  | COURT 5                                                      | Tashkent                   | Uzbekistan           | UZB            | Asia/Tashkent                  | sr:complex:44522 |
| sr:venue:1348  | COURT 3                                                      | Bucharest                  | Romania              | ROU            | Europe/Bucharest               | sr:complex:60416 |
| sr:venue:1349  | Centre Court                                                 | Seoul                      | Republic of Korea    | KOR            | Asia/Seoul                     | sr:complex:44520 |
| sr:venue:1350  | Court 2                                                      | Seoul                      | Republic of Korea    | KOR            | Asia/Seoul                     | sr:complex:44520 |
| sr:venue:1351  | Court 13                                                     | Seoul                      | Republic of Korea    | KOR            | Asia/Seoul                     | sr:complex:44520 |
| sr:venue:1352  | Court 11                                                     | Seoul                      | Republic of Korea    | KOR            | Asia/Seoul                     | sr:complex:61761 |
| sr:venue:13520 | Quadra Guga Kuerten                                          | Rio de Janeiro             | Brazil               | BRA            | Brazil/East                    | sr:complex:33296 |
| sr:venue:13524 | Quadra 2                                                     | Rio de Janeiro             | Brazil               | BRA            | Brazil/East                    | sr:complex:33296 |
| sr:venue:13564 | Grandstand                                                   | Acapulco                   | Mexico               | MEX            | America/Mexico_City            | sr:complex:77425 |
| sr:venue:1357  | Centre Court                                                 | Bangkok                    | Thailand             | THA            | Asia/Bangkok                   | sr:complex:33440 |
| sr:venue:1358  | Court 1                                                      | Bangkok                    | Thailand             | THA            | Asia/Bangkok                   | sr:complex:33440 |
| sr:venue:1364  | Center                                                       | Beijing                    | China                | CHN            | Asia/Shanghai                  | sr:complex:46526 |
| sr:venue:1365  | Court 1                                                      | Beijing                    | China                | CHN            | Asia/Shanghai                  | sr:complex:46526 |
| sr:venue:1366  | Court 4                                                      | Beijing                    | China                | CHN            | Asia/Shanghai                  | sr:complex:46526 |
| sr:venue:1367  | Court 5                                                      | Beijing                    | China                | CHN            | Asia/Shanghai                  | sr:complex:46526 |
| sr:venue:1368  | Court 7                                                      | Beijing                    | China                | CHN            | Asia/Shanghai                  | sr:complex:46526 |
| sr:venue:1369  | Court 8                                                      | Beijing                    | China                | CHN            | Asia/Shanghai                  | sr:complex:46526 |
| sr:venue:1370  | Court 9                                                      | Beijing                    | China                | CHN            | Asia/Shanghai                  | sr:complex:46526 |
| sr:venue:1371  | Court 2                                                      | Beijing                    | China                | CHN            | Asia/Shanghai                  | sr:complex:46526 |
| sr:venue:1374  | Grandstand                                                   | Shanghai                   | China                | CHN            | Asia/Shanghai                  | sr:complex:44518 |
| sr:venue:13744 | Estadio GNP Seguros                                          | Monterrey                  | Mexico               | MEX            | America/Mexico_City            | sr:complex:33292 |
| sr:venue:13746 | Cancha 1                                                     | Monterrey                  | Mexico               | MEX            | America/Mexico_City            | sr:complex:33292 |
| sr:venue:13748 | Cancha 2                                                     | Monterrey                  | Mexico               | MEX            | America/Mexico_City            | sr:complex:33292 |
| sr:venue:1376  | Court 4                                                      | Shanghai                   | China                | CHN            | Asia/Shanghai                  | sr:complex:44518 |
| sr:venue:1377  | Court 5                                                      | Shanghai                   | China                | CHN            | Asia/Shanghai                  | sr:complex:44518 |
| sr:venue:1378  | Stadium Court                                                | Shanghai                   | China                | CHN            | Asia/Shanghai                  | sr:complex:44518 |
| sr:venue:1379  | Center                                                       | Osaka                      | Japan                | JPN            | Asia/Tokyo                     | sr:complex:33254 |
| sr:venue:13796 | CENTRE COURT                                                 | Itajai                     | Brazil               | BRA            | America/Sao_Paulo              | sr:complex:86592 |
| sr:venue:1380  | Court 1                                                      | Osaka                      | Japan                | JPN            | Asia/Tokyo                     | sr:complex:33254 |
| sr:venue:13800 | COURT 3                                                      | Itajai                     | Brazil               | BRA            | America/Sao_Paulo              | sr:complex:86592 |
| sr:venue:13802 | COURT 4                                                      | Itajai                     | Brazil               | BRA            | America/Sao_Paulo              | sr:complex:86592 |
| sr:venue:1381  | Court 2                                                      | Osaka                      | Japan                | JPN            | Asia/Tokyo                     | sr:complex:33254 |
| sr:venue:1383  | Astana Arena                                                 | Astana                     | Kazakhstan           | KAZ            | Asia/Almaty                    | sr:complex:26985 |
| sr:venue:13830 | Cancha 1                                                     | Santiago                   | Chile                | CHL            | America/Santiago               | sr:complex:62419 |
| sr:venue:13832 | Cancha 3                                                     | Santiago                   | Chile                | CHL            | America/Santiago               | sr:complex:62419 |
| sr:venue:13834 | Cancha 8                                                     | San Luis de Potosi         | Mexico               | MEX            | America/Mexico_City            | sr:complex:39095 |
| sr:venue:13836 | Cancha Central                                               | San Luis de Potosi         | Mexico               | MEX            | America/Mexico_City            | sr:complex:39095 |
| sr:venue:13840 | Court 3                                                      | Sao Paulo                  | Brazil               | BRA            | America/Sao_Paulo              | sr:complex:61643 |
| sr:venue:13842 | Cancha 4                                                     | San Luis de Potosi         | Mexico               | MEX            | America/Mexico_City            | sr:complex:39095 |