In [1]:


from double_competitor_rankings import response
import json

data=json.loads(response.text)

doublecomrank = data['rankings']

competitor_ranking_list = []
for dubcomp in doublecomrank:
    for rank in dubcomp.get("competitor_rankings", []):
        comp = rank.get("competitor", [])
        competitor_ranking_list.append({
            "rank" : rank["rank"],
            "movement" : rank["movement"],
            "points" : rank["points"],
            "competitions_played" : rank["competitions_played"],
            "id" : comp["id"]
        })


competitors_list = []
for dubcomp in doublecomrank:
    for rank in dubcomp.get("competitor_rankings", []):
        comp = rank.get("competitor", [])
        competitors_list.append({
            "id" : comp["id"],
            "name" : comp["name"],
            "country" : comp.get("country"),
            "country_code" : comp.get("country_code"),
            "abbreviation" : comp.get("abbreviation"),
            "week" : dubcomp["week"],
            "Year" : dubcomp["year"]
        })

{"generated_at":"2026-08-06T08:25:47+00:00","rankings":[{"type_id":2,"name":"ATP","year":2026,"week":32,"gender":"men","competitor_rankings":[{"rank":1,"movement":0,"points":10050,"competitions_played":19,"competitor":{"id":"sr:competitor:14898","name":"Heliovaara, Harri","country":"Finland","country_code":"FIN","abbreviation":"HEL"}},{"rank":1,"movement":0,"points":10050,"competitions_played":19,"competitor":{"id":"sr:competitor:637970","name":"Patten, Henry","country":"Great Britain","country_code":"GBR","abbreviation":"PAT"}},{"rank":3,"movement":0,"points":7310,"competitions_played":13,"competitor":{"id":"sr:competitor:16160","name":"Zeballos, Horacio","country":"Argentina","country_code":"ARG","abbreviation":"ZEB"}},{"rank":4,"movement":0,"points":7310,"competitions_played":15,"competitor":{"id":"sr:competitor:15568","name":"Granollers, Marcel","country":"Spain","country_code":"ESP","abbreviation":"GRA"}},{"rank":5,"movement":0,"points":6540,"competitions_played":24,"competitor":{"id":"sr:competitor:53785","name":"Skupski, Neal","country":"Great Britain","country_code":"GBR","abbreviation":"SKU"}},{"rank":6,"movement":0,"points":5180,"competitions_played":26,"competitor":{"id":"sr:competitor:95801","name":"Vavassori, Andrea","country":"Italy","country_code":"ITA","abbreviation":"VAV"}},{"rank":7,"movement":0,"points":4960,"competitions_played":20,"competitor":{"id":"sr:competitor:51836","name":"Arevalo, Marcelo","country":"El Salvador","country_code":"SLV","abbreviation":"ARE"}},{"rank":8,"movement":0,"points":4960,"competitions_played":21,"competitor":{"id":"sr:competitor:49363","name":"Pavic, Mate","country":"Croatia","country_code":"HRV","abbreviation":"PAV"}},{"rank":9,"movement":4,"points":4790,"competitions_played":20,"competitor":{"id":"sr:competitor:15310","name":"Bolelli, Simone","country":"Italy","country_code":"ITA","abbreviation":"BOL"}},{"rank":10,"movement":-1,"points":4650,"competitions_played":19,"competitor":{"id":"sr:competitor:36593","name":"Krawietz, Kevin","country":"Germany","country_code":"DEU","abbreviation":"KRA"}},{"rank":11,"movement":-1,"points":4470,"competitions_played":17,"competitor":{"id":"sr:competitor:52293","name":"Putz, Tim","country":"Germany","country_code":"DEU","abbreviation":"PUT"}},{"rank":12,"movement":2,"points":4410,"competitions_played":25,"competitor":{"id":"sr:competitor:52065","name":"Harrison, Christian","country":"USA","country_code":"USA","abbreviation":"HAR"}},{"rank":13,"movement":-2,"points":4330,"competitions_played":23,"competitor":{"id":"sr:competitor:59131","name":"Glasspool, Lloyd","country":"Great Britain","country_code":"GBR","abbreviation":"GLA"}},{"rank":13,"movement":-2,"points":4330,"competitions_played":23,"competitor":{"id":"sr:competitor:108099","name":"Cash, Julian","country":"Great Britain","country_code":"GBR","abbreviation":"CAS"}},{"rank":15,"movement":0,"points":3835,"competitions_played":26,"competitor":{"id":"sr:competitor:121182","name":"Guinard, Manuel","country":"France","country_code":"FRA","abbreviation":"GUI"}},{"rank":16,"movement":0,"points":3745,"competitions_played":30,"competitor":{"id":"sr:competitor:47295","name":"Andreozzi, Guido","country":"Argentina","country_code":"ARG","abbreviation":"AND"}},{"rank":17,"movement":1,"points":3530,"competitions_played":25,"competitor":{"id":"sr:competitor:16608","name":"Mektic, Nikola","country":"Croatia","country_code":"HRV","abbreviation":"MEK"}},{"rank":18,"movement":-1,"points":3055,"competitions_played":16,"competitor":{"id":"sr:competitor:74173","name":"Salisbury, Joe","country":"Great Britain","country_code":"GBR","abbreviation":"SAL"}},{"rank":19,"movement":0,"points":3050,"competitions_played":32,"competitor":{"id":"sr:competitor:78793","name":"Miedler, Lucas","country":"Austria","country_code":"AUT","abbreviation":"MIE"}},{"rank":20,"movement":3,"points":2960,"competitions_played":27,"competitor":{"id":"sr:competitor:106349","name":"Reboul, Fabien","country":"France","country_code":"FRA","abbreviation":"REB"}},{"rank":21,"movement":3,"points":2960,"competitions_played":34,"competitor":{"id":"sr:competitor:106559","name":"Doumbia, Sadio","country":"France","country_code":"FRA","abbreviation":"DOU"}},{"rank":22,"movement":-2,"points":2930,"competitions_played":32,"competitor":{"id":"sr:competitor:47966","name":"Olivetti, Albano","country":"France","country_code":"FRA","abbreviation":"OLI"}},{"rank":23,"movement":-2,"points":2902,"competitions_played":23,"competitor":{"id":"sr:competitor:80665","name":"Polmans, Marc","country":"Australia","country_code":"AUS","abbreviation":"POL"}},{"rank":24,"movement":-2,"points":2900,"competitions_played":37,"competitor":{"id":"sr:competitor:231090","name":"Arribage, Theo","country":"France","country_code":"FRA","abbreviation":"ARR"}},{"rank":25,"movement":0,"points":2710,"competitions_played":25,"competitor":{"id":"sr:competitor:14835","name":"Roger-Vasselin, Edouard","country":"France","country_code":"FRA","abbreviation":"ROG"}},{"rank":26,"movement":0,"points":2710,"competitions_played":26,"competitor":{"id":"sr:competitor:52202","name":"Nys, Hugo","country":"Monaco","country_code":"MCO","abbreviation":"NYS"}},{"rank":27,"movement":0,"points":2610,"competitions_played":31,"competitor":{"id":"sr:competitor:127646","name":"Cabral, Francisco","country":"Portugal","country_code":"PRT","abbreviation":"CAB"}},{"rank":28,"movement":1,"points":2490,"competitions_played":26,"competitor":{"id":"sr:competitor:22967","name":"Bhambri, Yuki","country":"India","country_code":"IND","abbreviation":"BHA"}},{"rank":29,"movement":-1,"points":2400,"competitions_played":18,"competitor":{"id":"sr:competitor:44553","name":"Herbert, Pierre-Hugues","country":"France","country_code":"FRA","abbreviation":"HER"}},{"rank":30,"movement":1,"points":2350,"competitions_played":32,"competitor":{"id":"sr:competitor:838776","name":"Tracy, James","country":"USA","country_code":"USA","abbreviation":"TRA"}},{"rank":31,"movement":1,"points":2320,"competitions_played":31,"competitor":{"id":"sr:competitor:112969","name":"Schnaitter, Jakob","country":"Germany","country_code":"DEU","abbreviation":"SCH"}},{"rank":31,"movement":1,"points":2320,"competitions_played":31,"competitor":{"id":"sr:competitor:936355","name":"Wallner, Mark","country":"Germany","country_code":"DEU","abbreviation":"WAL"}},{"rank":33,"movement":-3,"points":2305,"competitions_played":28,"competitor":{"id":"sr:competitor:70348","name":"Goransson, Andre","country":"Sweden","country_code":"SWE","abbreviation":"GOR"}},{"rank":34,"movement":1,"points":2200,"competitions_played":25,"competitor":{"id":"sr:competitor:59324","name":"Pavlasek, Adam","country":"Czechia","country_code":"CZE","abbreviation":"PAV"}},{"rank":35,"movement":1,"points":2185,"competitions_played":24,"competitor":{"id":"sr:competitor:114831","name":"Erler, Alexander","country":"Austria","country_code":"AUT","abbreviation":"ERL"}},{"rank":36,"movement":1,"points":2185,"competitions_played":25,"competitor":{"id":"sr:competitor:152900","name":"Rikl, Patrik","country":"Czechia","country_code":"CZE","abbreviation":"RIK"}},{"rank":37,"movement":-3,"points":2180,"competitions_played":25,"competitor":{"id":"sr:competitor:112805","name":"Zielinski, Jan","country":"Poland","country_code":"POL","abbreviation":"ZIE"}},{"rank":38,"movement":8,"points":2170,"competitions_played":26,"competitor":{"id":"sr:competitor:25189","name":"Krajicek, Austin","country":"USA","country_code":"USA","abbreviation":"KRA"}},{"rank":39,"movement":-1,"points":2165,"competitions_played":33,"competitor":{"id":"sr:competitor:76263","name":"Matos, Rafael","country":"Brazil","country_code":"BRA","abbreviation":"MAT"}},{"rank":40,"movement":-1,"points":2100,"competitions_played":33,"competitor":{"id":"sr:competitor:111195","name":"Luz, Orlando","country":"Brazil","country_code":"BRA","abbreviation":"LUZ"}},{"rank":41,"movement":3,"points":2065,"competitions_played":31,"competitor":{"id":"sr:competitor:206889","name":"Galloway, Robert","country":"USA","country_code":"USA","abbreviation":"GAL"}},{"rank":42,"movement":-2,"points":2045,"competitions_played":30,"competitor":{"id":"sr:competitor:231188","name":"Frantzen, Constantin","country":"Germany","country_code":"DEU","abbreviation":"FRA"}},{"rank":43,"movement":-2,"points":2032,"competitions_played":29,"competitor":{"id":"sr:competitor:393598","name":"Cash, Robert","country":"USA","country_code":"USA","abbreviation":"CAS"}},{"rank":44,"movement":-2,"points":2015,"competitions_played":36,"competitor":{"id":"sr:competitor:280601","name":"Oberleitner, Neil","country":"Austria","country_code":"AUT","abbreviation":"OBE"}},{"rank":45,"movement":-2,"points":2000,"competitions_played":30,"competitor":{"id":"sr:competitor:16042","name":"Haase, Robin","country":"Netherlands","country_code":"NLD","abbreviation":"HAA"}},{"rank":46,"movement":-1,"points":1960,"competitions_played":24,"competitor":{"id":"sr:competitor:204781","name":"Nouza, Petr","country":"Czechia","country_code":"CZE","abbreviation":"NOU"}},{"rank":47,"movement":0,"points":1860,"competitions_played":26,"competitor":{"id":"sr:competitor:62410","name":"Johnson, Luke","country":"Great Britain","country_code":"GBR","abbreviation":"JOH"}},{"rank":48,"movement":7,"points":1760,"competitions_played":30,"competitor":{"id":"sr:competitor:16124","name":"Melo, Marcelo","country":"Brazil","country_code":"BRA","abbreviation":"MEL"}},{"rank":49,"movement":5,"points":1730,"competitions_played":33,"competitor":{"id":"sr:competitor:23899","name":"King, Evan","country":"USA","country_code":"USA","abbreviation":"KIN"}},{"rank":50,"movement":0,"points":1715,"competitions_played":30,"competitor":{"id":"sr:competitor:234124","name":"Stevens, Bart","country":"Netherlands","country_code":"NLD","abbreviation":"STE"}},{"rank":51,"movement":0,"points":1715,"competitions_played":31,"competitor":{"id":"sr:competitor:234044","name":"Kirkov, Vasil","country":"USA","country_code":"USA","abbreviation":"KIR"}},{"rank":52,"movement":4,"points":1660,"competitions_played":7,"competitor":{"id":"sr:competitor:90798","name":"Halys, Quentin","country":"France","country_code":"FRA","abbreviation":"HAL"}},{"rank":53,"movement":4,"points":1640,"competitions_played":29,"competitor":{"id":"sr:competitor:52951","name":"Pel, David","country":"Netherlands","country_code":"NLD","abbreviation":"PEL"}},{"rank":54,"movement":-5,"points":1630,"competitions_played":13,"competitor":{"id":"sr:competitor:14553","name":"Ram, Rajeev","country":"USA","country_code":"USA","abbreviation":"RAM"}},{"rank":55,"movement":-7,"points":1610,"competitions_played":29,"competitor":{"id":"sr:competitor:66864","name":"Arends, Sander","country":"Netherlands","country_code":"NLD","abbreviation":"ARE"}},{"rank":56,"movement":2,"points":1545,"competitions_played":16,"competitor":{"id":"sr:competitor:16151","name":"Venus, Michael","country":"New Zealand","country_code":"NZL","abbreviation":"VEN"}},{"rank":57,"movement":2,"points":1535,"competitions_played":31,"competitor":{"id":"sr:competitor:52244","name":"Balaji, N. Sriram","country":"India","country_code":"IND","abbreviation":"BAL"}},{"rank":58,"movement":3,"points":1441,"competitions_played":35,"competitor":{"id":"sr:competitor:204495","name":"Vocel, Matej","country":"Czechia","country_code":"CZE","abbreviation":"VOC"}},{"rank":59,"movement":3,"points":1415,"competitions_played":27,"competitor":{"id":"sr:competitor:16992","name":"Willis, Marcus","country":"Great Britain","country_code":"GBR","abbreviation":"WIL"}},{"rank":60,"movement":4,"points":1410,"competitions_played":27,"competitor":{"id":"sr:competitor:81059","name":"Gille, Sander","country":"Belgium","country_code":"BEL","abbreviation":"GIL"}},{"rank":61,"movement":17,"points":1404,"competitions_played":27,"competitor":{"id":"sr:competitor:1020797","name":"Trhac, Patrik","country":"USA","country_code":"USA","abbreviation":"TRH"}},{"rank":62,"movement":-10,"points":1395,"competitions_played":23,"competitor":{"id":"sr:competitor:15548","name":"Gonzalez, Maximo","country":"Argentina","country_code":"ARG","abbreviation":"GON"}},{"rank":63,"movement":-10,"points":1395,"competitions_played":24,"competitor":{"id":"sr:competitor:38181","name":"Molteni, Andres","country":"Argentina","country_code":"ARG","abbreviation":"MOL"}},{"rank":64,"movement":10,"points":1385,"competitions_played":37,"competitor":{"id":"sr:competitor:287215","name":"Seggerman, Ryan","country":"USA","country_code":"USA","abbreviation":"SEG"}},{"rank":65,"movement":0,"points":1381,"competitions_played":32,"competitor":{"id":"sr:competitor:16573","name":"Demoliner, Marcelo","country":"Brazil","country_code":"BRA","abbreviation":"DEM"}},{"rank":66,"movement":0,"points":1368,"competitions_played":27,"competitor":{"id":"sr:competitor:243522","name":"Paul, Jakub","country":"Switzerland","country_code":"CHE","abbreviation":"PAU"}},{"rank":67,"movement":-4,"points":1360,"competitions_played":30,"competitor":{"id":"sr:competitor:230186","name":"Verbeek, Sem","country":"Netherlands","country_code":"NLD","abbreviation":"VER"}},{"rank":68,"movement":-8,"points":1318,"competitions_played":26,"competitor":{"id":"sr:competitor:17038","name":"Smith, John-Patrick","country":"Australia","country_code":"AUS","abbreviation":"SMI"}},{"rank":69,"movement":-2,"points":1310,"competitions_played":32,"competitor":{"id":"sr:competitor:15588","name":"Rojer, Jean-Julien","country":"Netherlands","country_code":"NLD","abbreviation":"ROJ"}},{"rank":70,"movement":-2,"points":1300,"competitions_played":33,"competitor":{"id":"sr:competitor:15305","name":"Gonzalez, Santiago","country":"Mexico","country_code":"MEX","abbreviation":"GON"}},{"rank":71,"movement":-2,"points":1291,"competitions_played":37,"competitor":{"id":"sr:competitor:1015089","name":"Winegar, Theodore","country":"USA","country_code":"USA","abbreviation":"WIN"}},{"rank":72,"movement":5,"points":1225,"competitions_played":38,"competitor":{"id":"sr:competitor:422955","name":"Sanchez, Luca","country":"France","country_code":"FRA","abbreviation":"SAN"}},{"rank":73,"movement":-3,"points":1217,"competitions_played":26,"competitor":{"id":"sr:competitor:56629","name":"Peers, John","country":"Australia","country_code":"AUS","abbreviation":"PEE"}},{"rank":74,"movement":-1,"points":1216,"competitions_played":2,"competitor":{"id":"sr:competitor:39726","name":"Kubler, Jason","country":"Australia","country_code":"AUS","abbreviation":"KUB"}},{"rank":75,"movement":0,"points":1203,"competitions_played":32,"competitor":{"id":"sr:competitor:297448","name":"Kiger, Mac","country":"USA","country_code":"USA","abbreviation":"KIG"}},{"rank":76,"movement":4,"points":1190,"competitions_played":37,"competitor":{"id":"sr:competitor:180104","name":"Reymond, Arthur","country":"France","country_code":"FRA","abbreviation":"REY"}},{"rank":77,"movement":-1,"points":1182,"competitions_played":24,"competitor":{"id":"sr:competitor:41475","name":"Arneodo, Romain","country":"Monaco","country_code":"MCO","abbreviation":"ARN"}},{"rank":78,"movement":-7,"points":1166,"competitions_played":32,"competitor":{"id":"sr:competitor:108755","name":"Jebens, Hendrik","country":"Germany","country_code":"DEU","abbreviation":"JEB"}},{"rank":79,"movement":-7,"points":1166,"competitions_played":34,"competitor":{"id":"sr:competitor:256001","name":"Ho, Ray","country":"Chinese Taipei","country_code":"TPE","abbreviation":"RAY"}},{"rank":80,"movement":3,"points":1146,"competitions_played":35,"competitor":{"id":"sr:competitor:263865","name":"Reynolds, Finn","country":"New Zealand","country_code":"NZL","abbreviation":"REY"}},{"rank":81,"movement":3,"points":1146,"competitions_played":36,"competitor":{"id":"sr:competitor:973963","name":"Watt, James","country":"New Zealand","country_code":"NZL","abbreviation":"WAT"}},{"rank":82,"movement":-3,"points":1137,"competitions_played":34,"competitor":{"id":"sr:competitor:49306","name":"Reyes-Varela, Miguel Angel","country":"Mexico","country_code":"MEX","abbreviation":"REY"}},{"rank":83,"movement":-2,"points":1071,"competitions_played":30,"competitor":{"id":"sr:competitor:296270","name":"Stevenson, David","country":"Great Britain","country_code":"GBR","abbreviation":"STE"}},{"rank":84,"movement":1,"points":1026,"competitions_played":36,"competitor":{"id":"sr:competitor:614090","name":"Pieczonka, Filip","country":"Poland","country_code":"POL","abbreviation":"PIE"}},{"rank":85,"movement":1,"points":993,"competitions_played":31,"competitor":{"id":"sr:competitor:52263","name":"Hidalgo, Diego","country":"Ecuador","country_code":"ECU","abbreviation":"HID"}},{"rank":86,"movement":3,"points":986,"competitions_played":35,"competitor":{"id":"sr:competitor:145936","name":"Kaliyanda Poonacha, Niki","country":"India","country_code":"IND","abbreviation":"KAL"}},{"rank":87,"movement":13,"points":971,"competitions_played":38,"competitor":{"id":"sr:competitor:210736","name":"Lammons, Nathaniel","country":"USA","country_code":"USA","abbreviation":"LAM"}},{"rank":88,"movement":2,"points":965,"competitions_played":33,"competitor":{"id":"sr:competitor:16198","name":"Escobar, Gonzalo","country":"Ecuador","country_code":"ECU","abbreviation":"ESC"}},{"rank":89,"movement":2,"points":940,"competitions_played":37,"competitor":{"id":"sr:competitor:628034","name":"Kittay, Benjamin","country":"USA","country_code":"USA","abbreviation":"KIT"}},{"rank":90,"movement":-8,"points":930,"competitions_played":32,"competitor":{"id":"sr:competitor:16823","name":"Romboli, Fernando","country":"Brazil","country_code":"BRA","abbreviation":"ROM"}},{"rank":91,"movement":14,"points":930,"competitions_played":33,"competitor":{"id":"sr:competitor:209202","name":"Chandrasekar, Anirudh","country":"India","country_code":"IND","abbreviation":"CHA"}},{"rank":92,"movement":-4,"points":922,"competitions_played":36,"competitor":{"id":"sr:competitor:240880","name":"Hilderbrand, Trey","country":"USA","country_code":"USA","abbreviation":"HIL"}},{"rank":93,"movement":0,"points":916,"competitions_played":35,"competitor":{"id":"sr:competitor:59700","name":"Isaro, Pruchya","country":"Thailand","country_code":"THA","abbreviation":"ISA"}},{"rank":94,"movement":-2,"points":904,"competitions_played":33,"competitor":{"id":"sr:competitor:113889","name":"Liutarevich, Ivan","country":"Neutral","abbreviation":"LIU"}},{"rank":95,"movement":21,"points":897,"competitions_played":31,"competitor":{"id":"sr:competitor:55989","name":"Withrow, Jackson","country":"USA","country_code":"USA","abbreviation":"WIT"}},{"rank":96,"movement":-1,"points":893,"competitions_played":37,"competitor":{"id":"sr:competitor:121032","name":"Stalder, Reese","country":"USA","country_code":"USA","abbreviation":"STA"}},{"rank":97,"movement":-10,"points":889,"competitions_played":33,"competitor":{"id":"sr:competitor:48646","name":"Barrientos, Nicolas","country":"Colombia","country_code":"COL","abbreviation":"BAR"}},{"rank":98,"movement":-2,"points":885,"competitions_played":34,"competitor":{"id":"sr:competitor:95923","name":"Paris, Joshua","country":"Great Britain","country_code":"GBR","abbreviation":"PAR"}},{"rank":99,"movement":15,"points":877,"competitions_played":35,"competitor":{"id":"sr:competitor:272245","name":"Latinovic, Stefan","country":"Serbia","country_code":"SRB","abbreviation":"LAT"}},{"rank":100,"movement":1,"points":870,"competitions_played":35,"competitor":{"id":"sr:competitor:145008","name":"Uesugi, Kaito","country":"Japan","country_code":"JPN","abbreviation":"UES"}},{"rank":101,"movement":23,"points":860,"competitions_played":32,"competitor":{"id":"sr:competitor:45105","name":"Behar, Ariel","country":"Uruguay","country_code":"URY","abbreviation":"BEH"}},{"rank":102,"movement":-5,"points":852,"competitions_played":31,"competitor":{"id":"sr:competitor:548169","name":"Yuzuki, Takeru","country":"Japan","country_code":"JPN","abbreviation":"YUZ"}},{"rank":103,"movement":-5,"points":850,"competitions_played":2,"competitor":{"id":"sr:competitor:359602","name":"Musetti, Loren

In [2]:
import pandas as pd
competitor_ranking_df = pd.DataFrame(competitor_ranking_list)
competitor_ranking_df

     rank  movement  points  competitions_played                     id
0       1         0   10050                   19    sr:competitor:14898
1       1         0   10050                   19   sr:competitor:637970
2       3         0    7310                   13    sr:competitor:16160
3       4         0    7310                   15    sr:competitor:15568
4       5         0    6540                   24    sr:competitor:53785
..    ...       ...     ...                  ...                    ...
995   496        -6     147                   21  sr:competitor:1073852
996   496        -6     147                   21  sr:competitor:1073856
997   498        -6     146                   23   sr:competitor:226170
998   499        -6     145                   19   sr:competitor:153744
999   500        -6     145                   15   sr:competitor:448089

[1000 rows x 5 columns]

In [3]:
competitors_df = pd.DataFrame(competitors_list)
competitors_df

,id,name,country,country_code,abbreviation,week,Year
0,sr:competitor:14898,"Heliovaara, Harri",Finland,FIN,HEL,32,2026
1,sr:competitor:637970,"Patten, Henry",Great Britain,GBR,PAT,32,2026
2,sr:competitor:16160,"Zeballos, Horacio",Argentina,ARG,ZEB,32,2026
3,sr:competitor:15568,"Granollers, Marcel",Spain,ESP,GRA,32,2026
4,sr:competitor:53785,"Skupski, Neal",Great Britain,GBR,SKU,32,2026
...,...,...,...,...,...,...,...
995,sr:competitor:1073852,"Goncharova, Anastasia",USA,USA,GON,32,2026
996,sr:competitor:1073856,"Tattini, Madison",USA,USA,TAT,32,2026
997,sr:competitor:226170,"Urrutia, Maria Florencia",Argentina,ARG,URR,32,2026
998,sr:competitor:153744,"Pereira, Rebeca",Brazil,BRA,PER,32,2026
999,sr:competitor:448089,"Dittmann, Gina Marie",Germany,DEU,DIT,32,2026

In [4]:
competitor_ranking_d= competitor_ranking_df.drop_duplicates()
print(competitor_ranking_d)


competitor_ranking_d.to_csv("competitor_ranking.csv")

     rank  movement  points  competitions_played                     id
0       1         0   10050                   19    sr:competitor:14898
1       1         0   10050                   19   sr:competitor:637970
2       3         0    7310                   13    sr:competitor:16160
3       4         0    7310                   15    sr:competitor:15568
4       5         0    6540                   24    sr:competitor:53785
..    ...       ...     ...                  ...                    ...
995   496        -6     147                   21  sr:competitor:1073852
996   496        -6     147                   21  sr:competitor:1073856
997   498        -6     146                   23   sr:competitor:226170
998   499        -6     145                   19   sr:competitor:153744
999   500        -6     145                   15   sr:competitor:448089

[1000 rows x 5 columns]

In [5]:
competitors_d= competitors_df.drop_duplicates()
print(competitors_d)


competitors_d.to_csv("competitors.csv")

                        id                      name        country  \
0      sr:competitor:14898         Heliovaara, Harri        Finland
1     sr:competitor:637970             Patten, Henry  Great Britain
2      sr:competitor:16160         Zeballos, Horacio      Argentina
3      sr:competitor:15568        Granollers, Marcel          Spain
4      sr:competitor:53785             Skupski, Neal  Great Britain
..                     ...                       ...            ...
995  sr:competitor:1073852     Goncharova, Anastasia            USA
996  sr:competitor:1073856          Tattini, Madison            USA
997   sr:competitor:226170  Urrutia, Maria Florencia      Argentina
998   sr:competitor:153744           Pereira, Rebeca         Brazil
999   sr:competitor:448089      Dittmann, Gina Marie        Germany

    country_code abbreviation  week  Year
0            FIN          HEL    32  2026
1            GBR          PAT    32  2026
2            ARG          ZEB    32  2026
3            ESP          GRA    32  2026
4            GBR          SKU    32  2026
..           ...          ...   ...   ...
995          USA          GON    32  2026
996          USA          TAT    32  2026
997          ARG          URR    32  2026
998          BRA          PER    32  2026
999          DEU          DIT    32  2026

[1000 rows x 7 columns]

In [6]:
import mysql.connector

mydb = mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password="12@Musk@n4595",
    database="tennis_db"
)

cursor = mydb.cursor(buffered=True)

In [7]:
# Checking which column contain NaN value

print(competitors_df)
print(competitors_df[['id','name','country','country_code','abbreviation']].isna().sum())

                        id                      name        country  \
0      sr:competitor:14898         Heliovaara, Harri        Finland
1     sr:competitor:637970             Patten, Henry  Great Britain
2      sr:competitor:16160         Zeballos, Horacio      Argentina
3      sr:competitor:15568        Granollers, Marcel          Spain
4      sr:competitor:53785             Skupski, Neal  Great Britain
..                     ...                       ...            ...
995  sr:competitor:1073852     Goncharova, Anastasia            USA
996  sr:competitor:1073856          Tattini, Madison            USA
997   sr:competitor:226170  Urrutia, Maria Florencia      Argentina
998   sr:competitor:153744           Pereira, Rebeca         Brazil
999   sr:competitor:448089      Dittmann, Gina Marie        Germany

    country_code abbreviation  week  Year
0            FIN          HEL    32  2026
1            GBR          PAT    32  2026
2            ARG          ZEB    32  2026
3            ESP          GRA    32  2026
4            GBR          SKU    32  2026
..           ...          ...   ...   ...
995          USA          GON    32  2026
996          USA          TAT    32  2026
997          ARG          URR    32  2026
998          BRA          PER    32  2026
999          DEU          DIT    32  2026

[1000 rows x 7 columns]
id               0
name             0
country          0
country_code    50
abbreviation     0
dtype: int64

In [ ]:
from tabulate import tabulate
import math
Competitors_query = "INSERT INTO Competitors (competitor_id,name,country,country_code,abbreviation) VALUES(%s, %s,%s, %s, %s)"

competitors_data = competitors_df[
    ['id','name','country','country_code','abbreviation']
].values.tolist()

#Convert NaN to None
for row in competitors_data:
    for i,value in enumerate(row):
        if isinstance(value,float) and math.isnan(value):
            row[i] = None

print(competitors_data[0])

cursor.executemany(Competitors_query,competitors_data)
mydb.commit()

In [9]:
cursor.execute("SELECT COUNT(*) FROM competitors")
out=cursor.fetchall()
print(tabulate(out, headers=[i[0] for i in cursor.description],  tablefmt='psql'))

+------------+
|   COUNT(*) |
|------------|
|       1000 |
+------------+

In [10]:
cursor.execute("SELECT * FROM competitors")
out=cursor.fetchall()
print(tabulate(out,headers=[i[0] for i in cursor.description], tablefmt='psql'))

+-----------------------+--------------------------------------+--------------------------+----------------+----------------+
| competitor_id         | name                                 | country                  | country_code   | abbreviation   |
|-----------------------+--------------------------------------+--------------------------+----------------+----------------|
| sr:competitor:100069  | Sachko, Vitaliy                      | Ukraine                  | UKR            | SAC            |
| sr:competitor:100317  | Turker, Mert Naci                    | Turkiye                  | TUR            | TUR            |
| sr:competitor:1008651 | Adams, Julia                         | USA                      | USA            | ADA            |
| sr:competitor:1011445 | Exsted, Maxwell                      | USA                      | USA            | EXS            |
| sr:competitor:101157  | Rybakov, Alex                        | USA                      | USA            | RYB            |
| sr:competitor:1015089 | Winegar, Theodore                    | USA                      | USA            | WIN            |
| sr:competitor:1017327 | Samson, Laura                        | Czechia                  | CZE            | SAM            |
| sr:competitor:1020123 | Kovackova, Alena                     | Czechia                  | CZE            | KOV            |
| sr:competitor:1020177 | Huang, Yujia                         | China                    | CHN            | HUA            |
| sr:competitor:1020179 | Zhu, Chenting                        | China                    | CHN            | ZHU            |
| sr:competitor:1020369 | Oliveira, Bruno (2002)               | Brazil                   | BRA            | OLI            |
| sr:competitor:1020797 | Trhac, Patrik                        | USA                      | USA            | TRH            |
| sr:competitor:1020859 | Pawlikowska,  Zuzanna                | Poland                   | POL            | PAW            |
| sr:competitor:102151  | Tabilo, Alejandro                    | Chile                    | CHL            | TAB            |
| sr:competitor:1022815 | Akli, Ayana                          | USA                      | USA            | AKL            |
| sr:competitor:102339  | Van de Zandschulp, Botic             | Netherlands              | NLD            | VAN            |
| sr:competitor:1025093 | Bianchi, Juan Jose                   | Venezuela                | VEN            | BIA            |
| sr:competitor:102637  | McAdoo, Rasheeda                     | USA                      | USA            | MCA            |
| sr:competitor:1027515 | Du Pree, Britt                       | Netherlands              | NLD            | DU             |
| sr:competitor:1027521 | de Lange, Pieter                     | Netherlands              | NLD            | DE             |
| sr:competitor:103625  | Geerts, Michael                      | Belgium                  | BEL            | GEE            |
| sr:competitor:1038811 | Dyussebay, Ingkar                    | Kazakhstan               | KAZ            | DYU            |
| sr:competitor:103901  | Ruse, Elena-Gabriela                 | Romania                  | ROU            | RUS            |
| sr:competitor:1045543 | Bennemann, Eva                       | Germany                  | DEU            | BEN            |
| sr:competitor:1047289 | Sciahbasi, Matteo                    | Italy                    | ITA            | SCI            |
| sr:competitor:104847  | Sonego, Lorenzo                      | Italy                    | ITA            | SON            |
| sr:competitor:104917  | Vliegen, Joran                       | Belgium                  | BEL            | VLI            |
| sr:competitor:104929  | Tona, Miriana                        | Italy                    | ITA            | TON            |
| sr:competitor:105063  | Gavrila, Oana                        | Romania                  | ROU            | GAV            |
| sr:competitor:105099  | Birrell, Kimberly                    | Australia                | AUS            | BIR            |
| sr:competitor:1052227 | Maduzzi, Gaia                        | Italy                    | ITA            | MAD            |
| sr:competitor:105463  | Bouzkova, Marie                      | Czechia                  | CZE            | BOU            |
| sr:competitor:106341  | Knutson, Gabriela                    | Czechia                  | CZE            | KNU            |
| sr:competitor:106349  | Reboul, Fabien                       | France                   | FRA            | REB            |
| sr:competitor:106395  | Ricca, Giorgio                       | Italy                    | ITA            | RIC            |
| sr:competitor:106559  | Doumbia, Sadio                       | France                   | FRA            | DOU            |
| sr:competitor:106755  | Rublev, Andrey                       | Neutral                  |                | RUB            |
| sr:competitor:1073106 | Alicea, Samantha                     | USA                      | USA            | ALI            |
| sr:competitor:107327  | In-Albon, Ylena                      | Switzerland              | CHE            | IN-            |
| sr:competitor:1073852 | Goncharova, Anastasia                | USA                      | USA            | GON            |
| sr:competitor:1073856 | Tattini, Madison                     | USA                      | USA            | TAT            |
| sr:competitor:1080832 | Fuchs, Zachary                       | USA                      | USA            | FUC            |
| sr:competitor:108099  | Cash, Julian                         | Great Britain            | GBR            | CAS            |
| sr:competitor:108621  | Kempen, Magali                       | Belgium                  | BEL            | KEM            |
| sr:competitor:108755  | Jebens, Hendrik                      | Germany                  | DEU            | JEB            |
| sr:competitor:108767  | Hassan, Benjamin                     | Lebanon                  | LBN            | HAS            |
| sr:competitor:108857  | Lewis, Mary                          | USA                      | USA            | LEW            |
| sr:competitor:1098357 | Egorova, Daria                       | Neutral                  |                | EGO            |
| sr:competitor:110299  | Zidansek, Tamara                     | Slovenia                 | SVN            | ZID            |
| sr:competitor:110707  | Pichler, David                       | Austria                  | AUT            | PIC            |
| sr:competitor:1111195 | Remondy Pagotto, Victor Hugo         | Brazil                   | BRA            | REM            |
| sr:competitor:111149  | Samir, Sandra                        | Egypt                    | EGY            | SAM            |
| sr:competitor:111189  | Zarazua, Renata                      | Mexico                   | MEX            | ZAR            |
| sr:competitor:111195  | Luz, Orlando                         | Brazil                   | BRA            | LUZ            |
| sr:competitor:1115539 | Panshina, Varvara                    | Neutral                  |                | PAN            |
| sr:competitor:111607  | Ingildsen, Johannes                  | Denmark                  | DNK            | ING            |
| sr:competitor:111609  | Barroso Campos, Alberto              | Spain                    | ESP            | BAR            |
| sr:competitor:1116289 | Leme Da Silva, Nauhany Vitoria       | Brazil                   | BRA            | LEM            |
| sr:competitor:111767  | Nepliy, Elina                        | Neutral                  |                | NEP            |
| sr:competitor:112061  | Walkow, Szymon                       | Poland                   | POL            | WAL            |
| sr:competitor:112805  | Zielinski, Jan                       | Poland                   | POL            | ZIE            |
| sr:competitor:1128937 | Miguel, Luis Guto                    | Brazil                   | BRA            | MIG            |
| sr:competitor:112957  | Jeanjean, Leolia                     | France                   | FRA            | JEA            |
| sr:competitor:112969  | Schnaitter, Jakob                    | Germany                  | DEU            | SCH            |
| sr:competitor:113079  | Grabher, Julia                       | Austria                  | AUT            | GRA            |
| sr:competitor:113221  | Niklas-Salminen, Patrik              | Finland                  | FIN            | NIK            |
| sr:competitor:113889  | Liutarevich, Ivan                    | Neutral                  |                | LIU            |
| sr:competitor:114831  | Erler, Alexander                     | Austria                  | AUT            | ERL            |
| sr:competitor:114885  | Nikles, Johan                        | Switzerland              | CHE            | NIK            |
| sr:competitor:115239  | Kaukovalta, Patrick                  | Finland                  | FIN            | KAU            |
| sr:competitor:115507  | Bolsova, Aliona                      | Spain                    | ESP            | BOL            |
| sr:competitor:1164921 | Lombardini, Marta                    | Italy                    | ITA            | LOM            |
| sr:competitor:116616  | Clarke, Jay                          | Great Britain            | GBR            | CLA            |
| sr:competitor:117866  | Mukund, Sasikumar                    | India                    | IND            | MUK            |
| sr:competitor:118052  | Oz, Ipek                             | Turkiye                  | TUR            | IPE            |
| sr:competitor:119150  | Fancutt, Thomas                      | Australia                | AUS            | FAN            |
| sr:competitor:119216  | Herrero Linana, Alicia               | Spain                    | ESP            | HER            |
| sr:competitor:119670  | Perez, Ellen                         | Australia                | AUS            | PER            |
| sr:competitor:1196859 | Suarez, Billy                        | USA                      | USA            | SUA            |
| sr:competitor:120664  | Pedretti, Thaisa Grana               | Brazil                   | BRA            | PED            |
| sr:competitor:120722  | Alhussein Abdel Aziz, Lamis          | Egypt                    | EGY            | ALH            |
| sr:competitor:120956  | Alcantara, Francis Casey             | Philippines              | PHL            | ALC            |
| sr:competitor:121032  | Stalder, Reese                       | USA                      | USA            | STA            |
| sr:competitor:121182  | Guinard, Manuel                      | France                   | FRA            | GUI            |
| sr:competitor:121248  | Roveri Sidney, Gabriel               | Brazil                   | BRA            | ROV            |
| sr:competitor:121668  | Meligeni Alves, Felipe               | Brazil                   | BRA            | MEL            |
| sr:competitor:121760  | Anshba, Amina                        | Neutral                  |                | ANS            |
| sr:competitor:1222991 | Kovackova, Jana                      | Czechia                  | CZE            | KOV            |
| sr:competitor:122366  | Tsitsipas, Stefanos                  | Greece                   | GRC            | TSI            |
| sr:competitor:122368  | Griekspoor, Tallon                   | Netherlands              | NLD            | GRI            |
| sr:competitor:122668  | Daniel, Jaeda                        | USA                      | USA            | DAN            |
| sr:competitor:123824  | Dolehide, Caroline                   | USA                      | USA            | DOL            |
| sr:competitor:124708  | Cukierman, Daniel                    | Israel                   | ISR            | CUK            |
| sr:competitor:124934  | Lomakin, Grigoriy                    | Kazakhstan               | KAZ            | LOM            |
| sr:competitor:125006  | Borges, Nuno                         | Portugal                 | PRT            | BOR            |
| sr:competitor:126402  | Denolly, Corentin                    | France                   | FRA            | DEN            |
| sr:competitor:126622  | Ruehl, Tim                           | Germany                  | DEU            | RUE            |
| sr:competitor:127208  | Altmaier, Daniel                     | Germany                  | DEU            | ALT            |
| sr:competitor:127646  | Cabral, Francisco                    | Portugal                 | PRT            | CAB            |
| sr:competitor:1279439 | Breaz, Alesia                        | Romania                  | ROU            | BRE            |
| sr:competitor:128584  | Samsonova, Liudmila                  | Neutral                  |                | SAM            |
| sr:competitor:128638  | Sebov, Katherine                     | Canada                   | CAN            | SEB            |
| sr:competitor:129430  | Cervino Ruiz, Celia                  | Spain                    | ESP            | CER            |
| sr:competitor:129534  | Hruncakova, Viktoria                 | Slovakia                 | SVK            | HRU            |
| sr:competitor:129714  | Nicholls, Olivia                     | Great Britain            | GBR            | NIC            |
| sr:competitor:130442  | Rai, Ajeet                           | New Zealand              | NZL            | RAI            |
| sr:competitor:130494  | Neos, Eleftherios                    | Cyprus                   | CYP            | NEO            |
| sr:competitor:132370  | Kasatkina, Daria                     | Australia                | AUS            | KAS            |
| sr:competitor:132412  | Fita Boluda, Angela                  | Spain                    | ESP            | FIT            |
| sr:competitor:132558  | Kolar, Zdenek                        | Czechia                  | CZE            | KOL            |
| sr:competitor:133076  | Navarro Oliva, Maria Fernanda        | Mexico                   | MEX            | NAV            |
| sr:competitor:133080  | Hinojosa Gomez, Jessica              | Mexico                   | MEX            | HIN            |
| sr:competitor:134532  | You, Xiaodi                          | China                    | CHN            | YOU            |
| sr:competitor:135828  | Walters, Marcus                      | Great Britain            | GBR            | WAL            |
| sr:competitor:135854  | Neel, Ingrid                         | Estonia                  | EST            | NEE            |
| sr:competitor:137932  | Mikulskyte, Justina                  | Lithuania                | LTU            | MIK            |
| sr:competitor:138452  | Shibahara, Ena                       | Japan                    | JPN            | SHI            |
| sr:competitor:138654  | Duerst, Jenny                        | Switzerland              | CHE            | DUE            |
| sr:competitor:138712  | Oradini, Giovanni                    | Italy                    | ITA            | ORA            |
| sr:competitor:141882  | Blancaneaux, Geoffrey                | France                   | FRA            | BLA            |
| sr:competitor:141892  | Carle, Maria                         | Argentina                | ARG            | CAR            |
| sr:competitor:142758  | Zhang, Ying                          | China                    | CHN            | ZHA            |
| sr:competitor:142996  | Mihalikova, Tereza                   | Slovakia                 | SVK            | MIH            |
| sr:competitor:143140  | Aney, Jessie                         | USA                      | USA            | ANE            |
| sr:competitor:143146  | Smith, Alana                         | USA                      | USA            | SMI            |
| sr:competitor:145008  | Uesugi, Kaito                        | Japan                    | JPN            | UES            |
| sr:competitor:145112  | Huesler, Marc-Andrea                 | Switzerland              | CHE            | HUE            |
| sr:competitor:145122  | Martineau, Matteo                    | France                   | FRA            | MAR            |
| sr:competitor:14553   | Ram, Rajeev                          | USA                      | USA            | RAM            |
| sr:competitor:145936  | Kaliyanda Poonacha, Niki             | India                    | IND            | KAL            |
| sr:competitor:146040  | Gomez, Federico Agustin              | Argentina                | ARG            | GOM            |
| sr:competitor:147104  | Romios, Matthew Christopher          | Australia                | AUS            | ROM            |
| sr:competitor:148276  | Zheng, Wushuang                      | China                    | CHN            | ZHE            |
| sr:competitor:14835   | Roger-Vasselin, Edouard              | France                   | FRA            | ROG            |
| sr:competitor:14898   | Heliovaara, Harri                    | Finland                  | FIN            | HEL            |
| sr:competitor:150122  | Jiang, Xinyu                         | China                    | CHN            | JIA            |
| sr:competitor:150574  | Bondar, Anna                         | Hungary                  | HUN            | BON            |
| sr:competitor:152106  | Zaar, Lisa                           | Sweden                   | SWE            | ZAA            |
| sr:competitor:152708  | Brune Olsen, Astrid Wanja            | Norway                   | NOR            | BRU            |
| sr:competitor:152804  | Vondrousova, Marketa                 | Czechia                  | CZE            | VON            |
| sr:competitor:152900  | Rikl, Patrik                         | Czechia                  | CZE            | RIK            |
| sr:competitor:15305   | Gonzalez, Santiago                   | Mexico                   | MEX            | GON            |
| sr:competitor:15310   | Bolelli, Simone                      | Italy                    | ITA            | BOL            |
| sr:competitor:153652  | Guo, Hanyu                           | China                    | CHN            | GUO            |
| sr:competitor:153744  | Pereira, Rebeca                      | Brazil                   | BRA            | PER            |
| sr:competitor:154490  | Pearson, Kody                        | Australia                | AUS            | PEA            |
| sr:competitor:154740  | Delaney, Jesse                       | Australia                | AUS            | DEL            |
| sr:competitor:154744  | Lee, Eunhye (2000)                   | Republic of Korea        | KOR            | LEE            |
| sr:competitor:15548   | Gonzalez, Maximo                     | Argentina                | ARG            | GON            |
| sr:competitor:15568   | Granollers, Marcel                   | Spain                    | ESP            | GRA            |
| sr:competitor:155860  | Lock, Courtney John                  | Zimbabwe                 | ZWE            | LOC            |
| sr:competitor:15588   | Rojer, Jean-Julien                   | Netherlands              | NLD            | ROJ            |
| sr:competitor:156040  | Cho, I-Hsuan                         | Chinese Taipei           | TPE            | CHO            |
| sr:competitor:157368  | Kazionova, Ekaterina                 | Neutral                  |                | KAZ            |
| sr:competitor:157396  | Veldheer, Mick                       | Netherlands              | NLD            | VEL            |

In [15]:
Competitor_rankings_querey = "INSERT INTO Competitor_rankings (rank_position,movement,points,competitions_played,competitor_id) VALUES(%s, %s, %s, %s, %s)"

Competitor_rankings_data = competitor_ranking_d[['rank','movement','points','competitions_played','id']].values.tolist()

cursor.executemany(Competitor_rankings_querey, Competitor_rankings_data)
mydb.commit()

In [16]:
cursor.execute("SELECT COUNT(*) FROM Competitor_rankings")
out=cursor.fetchall()
print(tabulate(out,headers=[i[0] for i in cursor.description], tablefmt='psql'))

+------------+
|   COUNT(*) |
|------------|
|       1000 |
+------------+

In [17]:
cursor.execute("SELECT * FROM Competitor_rankings")
out=cursor.fetchall()
print(tabulate(out,headers=[i[0] for i in cursor.description], tablefmt='psql'))

+-----------+-----------------+------------+----------+-----------------------+-----------------------+
|   rank_id |   rank_position |   movement |   points |   competitions_played | competitor_id         |
|-----------+-----------------+------------+----------+-----------------------+-----------------------|
|         1 |               1 |          0 |    10050 |                    19 | sr:competitor:14898   |
|         2 |               1 |          0 |    10050 |                    19 | sr:competitor:637970  |
|         3 |               3 |          0 |     7310 |                    13 | sr:competitor:16160   |
|         4 |               4 |          0 |     7310 |                    15 | sr:competitor:15568   |
|         5 |               5 |          0 |     6540 |                    24 | sr:competitor:53785   |
|         6 |               6 |          0 |     5180 |                    26 | sr:competitor:95801   |
|         7 |               7 |          0 |     4960 |                    20 | sr:competitor:51836   |
|         8 |               8 |          0 |     4960 |                    21 | sr:competitor:49363   |
|         9 |               9 |          4 |     4790 |                    20 | sr:competitor:15310   |
|        10 |              10 |         -1 |     4650 |                    19 | sr:competitor:36593   |
|        11 |              11 |         -1 |     4470 |                    17 | sr:competitor:52293   |
|        12 |              12 |          2 |     4410 |                    25 | sr:competitor:52065   |
|        13 |              13 |         -2 |     4330 |                    23 | sr:competitor:59131   |
|        14 |              13 |         -2 |     4330 |                    23 | sr:competitor:108099  |
|        15 |              15 |          0 |     3835 |                    26 | sr:competitor:121182  |
|        16 |              16 |          0 |     3745 |                    30 | sr:competitor:47295   |
|        17 |              17 |          1 |     3530 |                    25 | sr:competitor:16608   |
|        18 |              18 |         -1 |     3055 |                    16 | sr:competitor:74173   |
|        19 |              19 |          0 |     3050 |                    32 | sr:competitor:78793   |
|        20 |              20 |          3 |     2960 |                    27 | sr:competitor:106349  |
|        21 |              21 |          3 |     2960 |                    34 | sr:competitor:106559  |
|        22 |              22 |         -2 |     2930 |                    32 | sr:competitor:47966   |
|        23 |              23 |         -2 |     2902 |                    23 | sr:competitor:80665   |
|        24 |              24 |         -2 |     2900 |                    37 | sr:competitor:231090  |
|        25 |              25 |          0 |     2710 |                    25 | sr:competitor:14835   |
|        26 |              26 |          0 |     2710 |                    26 | sr:competitor:52202   |
|        27 |              27 |          0 |     2610 |                    31 | sr:competitor:127646  |
|        28 |              28 |          1 |     2490 |                    26 | sr:competitor:22967   |
|        29 |              29 |         -1 |     2400 |                    18 | sr:competitor:44553   |
|        30 |              30 |          1 |     2350 |                    32 | sr:competitor:838776  |
|        31 |              31 |          1 |     2320 |                    31 | sr:competitor:112969  |
|        32 |              31 |          1 |     2320 |                    31 | sr:competitor:936355  |
|        33 |              33 |         -3 |     2305 |                    28 | sr:competitor:70348   |
|        34 |              34 |          1 |     2200 |                    25 | sr:competitor:59324   |
|        35 |              35 |          1 |     2185 |                    24 | sr:competitor:114831  |
|        36 |              36 |          1 |     2185 |                    25 | sr:competitor:152900  |
|        37 |              37 |         -3 |     2180 |                    25 | sr:competitor:112805  |
|        38 |              38 |          8 |     2170 |                    26 | sr:competitor:25189   |
|        39 |              39 |         -1 |     2165 |                    33 | sr:competitor:76263   |
|        40 |              40 |         -1 |     2100 |                    33 | sr:competitor:111195  |
|        41 |              41 |          3 |     2065 |                    31 | sr:competitor:206889  |
|        42 |              42 |         -2 |     2045 |                    30 | sr:competitor:231188  |
|        43 |              43 |         -2 |     2032 |                    29 | sr:competitor:393598  |
|        44 |              44 |         -2 |     2015 |                    36 | sr:competitor:280601  |
|        45 |              45 |         -2 |     2000 |                    30 | sr:competitor:16042   |
|        46 |              46 |         -1 |     1960 |                    24 | sr:competitor:204781  |
|        47 |              47 |          0 |     1860 |                    26 | sr:competitor:62410   |
|        48 |              48 |          7 |     1760 |                    30 | sr:competitor:16124   |
|        49 |              49 |          5 |     1730 |                    33 | sr:competitor:23899   |
|        50 |              50 |          0 |     1715 |                    30 | sr:competitor:234124  |
|        51 |              51 |          0 |     1715 |                    31 | sr:competitor:234044  |
|        52 |              52 |          4 |     1660 |                     7 | sr:competitor:90798   |
|        53 |              53 |          4 |     1640 |                    29 | sr:competitor:52951   |
|        54 |              54 |         -5 |     1630 |                    13 | sr:competitor:14553   |
|        55 |              55 |         -7 |     1610 |                    29 | sr:competitor:66864   |
|        56 |              56 |          2 |     1545 |                    16 | sr:competitor:16151   |
|        57 |              57 |          2 |     1535 |                    31 | sr:competitor:52244   |
|        58 |              58 |          3 |     1441 |                    35 | sr:competitor:204495  |
|        59 |              59 |          3 |     1415 |                    27 | sr:competitor:16992   |
|        60 |              60 |          4 |     1410 |                    27 | sr:competitor:81059   |
|        61 |              61 |         17 |     1404 |                    27 | sr:competitor:1020797 |
|        62 |              62 |        -10 |     1395 |                    23 | sr:competitor:15548   |
|        63 |              63 |        -10 |     1395 |                    24 | sr:competitor:38181   |
|        64 |              64 |         10 |     1385 |                    37 | sr:competitor:287215  |
|        65 |              65 |          0 |     1381 |                    32 | sr:competitor:16573   |
|        66 |              66 |          0 |     1368 |                    27 | sr:competitor:243522  |
|        67 |              67 |         -4 |     1360 |                    30 | sr:competitor:230186  |
|        68 |              68 |         -8 |     1318 |                    26 | sr:competitor:17038   |
|        69 |              69 |         -2 |     1310 |                    32 | sr:competitor:15588   |
|        70 |              70 |         -2 |     1300 |                    33 | sr:competitor:15305   |
|        71 |              71 |         -2 |     1291 |                    37 | sr:competitor:1015089 |
|        72 |              72 |          5 |     1225 |                    38 | sr:competitor:422955  |
|        73 |              73 |         -3 |     1217 |                    26 | sr:competitor:56629   |
|        74 |              74 |         -1 |     1216 |                     2 | sr:competitor:39726   |
|        75 |              75 |          0 |     1203 |                    32 | sr:competitor:297448  |
|        76 |              76 |          4 |     1190 |                    37 | sr:competitor:180104  |
|        77 |              77 |         -1 |     1182 |                    24 | sr:competitor:41475   |
|        78 |              78 |         -7 |     1166 |                    32 | sr:competitor:108755  |
|        79 |              79 |         -7 |     1166 |                    34 | sr:competitor:256001  |
|        80 |              80 |          3 |     1146 |                    35 | sr:competitor:263865  |
|        81 |              81 |          3 |     1146 |                    36 | sr:competitor:973963  |
|        82 |              82 |         -3 |     1137 |                    34 | sr:competitor:49306   |
|        83 |              83 |         -2 |     1071 |                    30 | sr:competitor:296270  |
|        84 |              84 |          1 |     1026 |                    36 | sr:competitor:614090  |
|        85 |              85 |          1 |      993 |                    31 | sr:competitor:52263   |
|        86 |              86 |          3 |      986 |                    35 | sr:competitor:145936  |
|        87 |              87 |         13 |      971 |                    38 | sr:competitor:210736  |
|        88 |              88 |          2 |      965 |                    33 | sr:competitor:16198   |
|        89 |              89 |          2 |      940 |                    37 | sr:competitor:628034  |
|        90 |              90 |         -8 |      930 |                    32 | sr:competitor:16823   |
|        91 |              91 |         14 |      930 |                    33 | sr:competitor:209202  |
|        92 |              92 |         -4 |      922 |                    36 | sr:competitor:240880  |
|        93 |              93 |          0 |      916 |                    35 | sr:competitor:59700   |
|        94 |              94 |         -2 |      904 |                    33 | sr:competitor:113889  |
|        95 |              95 |         21 |      897 |                    31 | sr:competitor:55989   |
|        96 |              96 |         -1 |      893 |                    37 | sr:competitor:121032  |
|        97 |              97 |        -10 |      889 |                    33 | sr:competitor:48646   |
|        98 |              98 |         -2 |      885 |                    34 | sr:competitor:95923   |
|        99 |              99 |         15 |      877 |                    35 | sr:competitor:272245  |
|       100 |             100 |          1 |      870 |                    35 | sr:competitor:145008  |
|       101 |             101 |         23 |      860 |                    32 | sr:competitor:45105   |
|       102 |             102 |         -5 |      852 |                    31 | sr:competitor:548169  |
|       103 |             103 |         -5 |      850 |                     2 | sr:competitor:359602  |
|       104 |             104 |         -5 |      850 |                     4 | sr:competitor:104847  |
|       105 |             105 |         -3 |      834 |                    33 | sr:competitor:90110   |
|       106 |             106 |         -3 |      832 |                    30 | sr:competitor:99377   |
|       107 |             107 |         -3 |      825 |                     3 | sr:competitor:863319  |
|       108 |             108 |         -1 |      824 |                    33 | sr:competitor:163538  |
|       109 |             109 |         -1 |      810 |                     3 | sr:competitor:188321  |
|       110 |             110 |         -1 |      810 |                    28 | sr:competitor:113221  |
|       111 |             111 |          0 |      800 |                     5 | sr:competitor:158912  |
|       112 |             112 |         -6 |      775 |                    35 | sr:competitor:295508  |
|       113 |             113 |          4 |      770 |                    13 | sr:competitor:57163   |
|       114 |             114 |          4 |      750 |                     8 | sr:competitor:63606   |
|       115 |             115 |          4 |      742 |                    30 | sr:competitor:98413   |
|       116 |             116 |          4 |      740 |                     3 | sr:competitor:71280   |
|       117 |             117 |         -4 |      739 |                    21 | sr:competitor:405969  |
|       118 |             118 |         -8 |      731 |                    31 | sr:competitor:450383  |
|       119 |             119 |         -7 |      720 |                    36 | sr:competitor:92845   |
|       120 |             120 |          1 |      719 |                    28 | sr:competitor:42151   |
|       121 |             121 |          8 |      716 |                    33 | sr:competitor:223868  |
|       122 |             122 |          1 |      709 |                    34 | sr:competitor:310972  |
|       123 |             123 |          3 |      701 |                    37 | sr:competitor:37637   |
|       124 |             124 |          1 |      701 |                    39 | sr:competitor:98981   |
|       125 |             125 |        -31 |      700 |                     6 | sr:competitor:808628  |
|       126 |             126 |         12 |      697 |                    25 | sr:competitor:437794  |
|       127 |             127 |         -5 |      695 |                    27 | sr:competitor:505542  |
|       128 |             128 |          0 |      692 |                    34 | sr:competitor:157396  |
|       129 |             129 |        -14 |      690 |                     9 | sr:competitor:871495  |
|       130 |             130 |          0 |      679 |                    29 | sr:competitor:124708  |
|       131 |             131 |         -4 |      673 |                    32 | sr:competitor:233144  |
|       132 |             132 |          9 |      672 |                    33 | sr:competitor:739643  |
|       133 |             133 |         -1 |      657 |                    36 | sr:competitor:161220  |
|       134 |             134 |         -3 |      655 |                    32 | sr:competitor:112061  |
|       135 |             135 |          0 |      654 |                    22 | sr:competitor:918463  |
|       136 |             136 |         10 |      651 |                    35 | sr:competitor:390480  |
|       137 |             137 |         -1 |      650 |                    11 | sr:competitor:300540  |
|       138 |             138 |         -1 |      650 |                    38 | sr:competitor:126622  |
|       139 |             139 |          1 |      637 |                    37 | sr:competitor:77011   |
|       140 |             140 |         -6 |      635 |                    31 | sr:competitor:111607  |
|       141 |             141 |          9 |      633 |                    37 | sr:competitor:60614   |
|       142 |             142 |          0 |      630 |                     6 | sr:competitor:106755  |
|       143 |             143 |          0 |      630 |                     7 | sr:competitor:90080   |
|       144 |             144 |          0 |      630 |                    10 | sr:competitor:122368  |
|       145 |             145 |        -12 |      628 |                    22 | sr:competitor:628218  |
|       146 |             146 |         -1 |      627 |                    24 | sr:competitor:147104  |
|       147 |             147 |         -8 |      626 |                    29 | sr:competitor:380004  |
|       148 |             148 |         -1 |      618 |                    19 | sr:competitor:110707  |
|       149 |             149 |         13 |      616 |                    31 | sr:competitor:16854   |
|       150 |             150 |         10 |      614 |                    35 | sr:competitor:25021   |
|       151 |             151 |         -3 |      607 |                    35 | sr:competitor:76361   |
|       152 |             152 |         -3 |      599 |                    25 | sr:competitor:73572   |
|       153 |             153 |         -1 |      592 |                    35 | sr:competitor:322589  |
|       154 |             154 |         -1 |      588 |                    35 | sr:competitor:54609   |
|       155 |             155 |         -1 |      584 |                    26 | sr:competitor:628226  |
|       156 |             156 |         -5 |      582 |                    34 | sr:competitor:880089  |
|       157 |             157 |         -1 |      572 |                    16 | sr:competitor:809324  |
|       158 |             158 |         -1 |      569 |                    33 | sr:competitor:77653   |
|       159 |             159 |         -1 |      568 |                    30 | sr:competitor:292414  |
|       160 |             160 |         -1 |      560 |                    26 | sr:competitor:497320  |
|       161 |             161 |         -6 |      560 |                    38 | sr:competitor:731833  |
|       162 |             162 |          3 |      546 |                    27 | sr:competitor:660427  |
|       163 |             163 |         -2 |      531 |                    34 | sr:competitor:297502  |
|       164 |             164 |         13 |      527 |                    29 | sr:competitor:53759   |
|       165 |             165 |          3 |      521 |                    32 | sr:competitor:208123  |
|       166 |             166 |         -3 |      519 |                    17 | sr:competitor:210592  |
|       167 |             167 |         -3 |      513 |                    35 | sr:competitor:161448  |
|       168 |             168 |         -2 |      506 |                    27 | sr:competitor:853643  |
|       169 |             169 |         -2 |      484 |                    31 | sr:competitor:79223   |
|       170 |             170 |         10 |      482 |                    26 | sr:competitor:63446   |
|       171 |             171 |         -2 |      475 |                     3 | sr:competitor:309954  |
|       172 |             172 |         -2 |      467 |                    34 | sr:competitor:50148   |
|       173 |             173 |         -2 |      467 |                    37 | sr:competitor:58877   |
|       174 |             174 |         -2 |      466 |                    31 | sr:competitor:272273  |
|       175 |             175 |         -2 |      456 |                    22 | sr:competitor:185434  |
|       176 |             176 |          6 |      454 |                    25 | sr:competitor:25458   |
|       177 |             177 |         -2 |      453 |                    14 | sr:competitor:38180   |
|       178 |             178 |         -2 |      453 |                    29 | sr:competitor:210636  |
|       179 |             179 |         -1 |      450 |                    14 | sr:competitor:169496  |
|       180 |             180 |         -1 |      438 |                    35 | sr:competitor:52260   |
|       181 |             181 |          7 |      435 |                    33 | sr:competitor:202735  |
|       182 |             182 |         -1 |      431 |                    28 | sr:competitor:322801  |
|       183 |             183 |         -9 |      429 |                     9 | sr:competitor:1128937 |
|       184 |             184 |          5 |      427 |                    23 | sr:competitor:348308  |
|       185 |             185 |          9 |      425 |                    15 | sr:competitor:299130  |
|       186 |             186 |         -3 |      423 |                     9 | sr:competitor:168420  |
|       187 |             187 |         -2 |      406 |                    21 | sr:competitor:44637   |
|       188 |             188 |         -2 |      405 |                    16 | sr:competitor:534043  |
|       189 |             189 |         -2 |      405 |                    19 | sr:competitor:927343  |